### ISSUE TITLE
`52.230.121.169` host isn't returning any data when anything other than `/` is requested

### ISSUE THREAD

**Issue by cailyoung** [microsoft/linux-package-repositories#104]
**Describe the issue**
Our VM image build process queries the `packages.microsoft.com` repo to install PowerShell.

For the build runners, this domain resolves to `52.230.121.169`, which fails to send any data on any request other than `/`

**When did the issue occur?**
As of 30 November 2023. Before then, our CI runners were being returned a different IP (`20.188.102.6`)

**If applicable, what package did you attempt to install, and from which repo?**
`/config/debian/10/packages-microsoft-prod.deb`

**Steps to Reproduce**
`wget https://52.230.121.169/config/debian/10/packages-microsoft-prod.deb --no-check-certificate`

**Actual Result**

Retries that all fail.

**Expected Result**

The `.deb` is returned.

**Screenshots**

**Additional context**
When I attempt this locally I get a different host (CDN node, presumably) which appears to work. The issue is still occurring, stably, for our CI runners.

**Comment by daviddavis** [comment]
@cailyoung the reproducer seems to work for me. are you still hitting the issue?

We deployed some fixes today that might've addressed this issue.

**Comment by cailyoung** [comment]
@daviddavis it appears to be working again now, thanks for following up.
