### ISSUE TITLE
Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-arm64/Packages.gz

### ISSUE THREAD

**Issue by jeremielalanne** [microsoft/linux-package-repositories#105]
**Describe the issue**
When adding MS packages:
```
echo "Adding Microsoft packages"
ms_pkgs_dir=/tmp/ms_pkgs
mkdir -p $ms_pkgs_dir
curl https://packages.microsoft.com/config/ubuntu/$ubuntu_version_url/prod.list > $ms_pkgs_dir/microsoft-prod.list
cp $ms_pkgs_dir/microsoft-prod.list /etc/apt/sources.list.d/
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > $ms_pkgs_dir/microsoft.gpg
cp $ms_pkgs_dir/microsoft.gpg /etc/apt/trusted.gpg.d/
apt update -y
```

> Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-arm64/Packages.gz

**When did the issue occur?**
Not sure of when it started, but first had the error yesterday

**Actual Result**

**Expected Result**

**Screenshots**
![image](https://github.com/microsoft/linux-package-repositories/assets/139769656/c2fb9bd9-3811-404a-811e-1e8ac02a5eb9)
![image](https://github.com/microsoft/linux-package-repositories/assets/139769656/19e73eec-a7b6-43e4-93cc-981cff00512e)

**Additional context**
In an Azure DevOps Pipeline

**Comment by mbearup** [comment]
@jeremielalanne thanks for reporting this issue. We've identified the cause and are working on a fix.
This specific instance was due to a mirror with a stale Packages.gz file, which is now fixed. Let us know if you continue experiencing issues.
