### ISSUE TITLE
Invalid/expired certificate for Debian 10 Prod Buster Release

### ISSUE THREAD

**Issue by nsepetys** [microsoft/linux-package-repositories#106]
Appears we're missing a valid certificate for debian 10 prod buster release  https://packages.microsoft.com/debian/10/prod buster

Architecture: AMD64
**When did the issue occur?**
Noticed it in the last few days.

**If applicable, what package did you attempt to install, and from which repo?**
 https://packages.microsoft.com/debian/10/prod buster

```
#8 9.485 Err:4 https://packages.microsoft.com/debian/10/prod buster Release     
#8 9.485   Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 13.93.152.112 443]
```

**Comment by jasonzio** [comment]
Please make sure you've installed the ca-certificates package; you need that to establish trust with various root CAs.

(We've confirmed the validity of the cert on that server.)

**Comment by nsepetys** [comment]
Not seeing the cert issue anymore. Thanks @jasonzio
