### ISSUE TITLE
RHEL8 -  Downloading entire repo to repomanager  give gpg error on  aadsshlogin-1.0.016820001-1.x86_64.rpm

### ISSUE THREAD

**Issue by jcengelsen** [microsoft/linux-package-repositories#109]
**Describe the issue**
Im trying to download the entire repo to create a mirror with repomanager

I use this config file to get the GPG and point to repo.  
It starts with everything works fine, but this aadssshlogin package give an error.
Even other versions of this package is downloaded, but not this one. 

Packages/a/aadsshlogin-1.0.016820001-1.x86_64.rpm ... KO GPG signature is not OK (unknown GPG signing key ID: 3135ce90)

Here is the information I use to dowload : 
[rhel8prod]
name=rhel/8/prod
baseurl=https://packages.microsoft.com/rhel/8/prod/
repo_gpgcheck=0
gpgcheck=0
enabled=1
gpgkey=https://packages.microsoft.com/rhel/8/prod/repodata/repomd.xml.key

**When did the issue occur?**
When downloading the entire repo with repomanager

**Screenshots**
![image](https://github.com/microsoft/linux-package-repositories/assets/26761328/265ea3f6-eb40-4085-8ce9-61c9bf0fe8c1)

**Comment by sdherr** [comment]
This package is signed with the CBL-Mariner signing key, which is a valid key for CBL-Mariner repositories but should not be here. We'll work with the publishing team to get this package correctly-signed and republished.

**Comment by sdherr** [comment]
This appears to have been purged. Let us know if you have other issues.
