### ISSUE TITLE
dnf repo: download is atrociously slow

### ISSUE THREAD

**Issue by stereomato** [microsoft/linux-package-repositories#111]
**Describe the issue**
Downloading VScode from the repo that MS offers for RHEL/CentOS/Fedora/etc is very slow. 
The download speed goes up slowly, but always starts at 300~ KB/s.
My connection maxes out at 6MB/s.

**When did the issue occur?**
Forever, only now I've decided to report it.

**If applicable, what package did you attempt to install, and from which repo?**
VScode, from its repo in the guide for linux, RHEL/CentOS/Fedora.

**Steps to Reproduce**
1. do the steps listed in the guide
2. see how code download goes

**Actual Result**
Very slow download.

**Expected Result**
A fast download.

**Screenshots**
![image](https://github.com/microsoft/linux-package-repositories/assets/132031693/5e48676c-f99b-4691-bf59-e8af06c13a6c)

**Additional context**

**Comment by acheng-01** [comment]
Hello @stereomato, thank you for bringing this to our attention. We are aware that slow download speeds have been an ongoing concern. Please know that we are actively working on this issue and should have a fix that will mitigate this problem soon.

I am also closing this issue out as a duplicate to a similar open issue. Will recommend following that thread for any further updates. Thank you for your patience!

#50
