### ISSUE TITLE
install_linux_azcmagent.sh: error installing azcmagent (exit code: 100)

### ISSUE THREAD

**Issue by reggaeshark888** [microsoft/linux-package-repositories#115]
**Describe the issue**
I am trying to install the Arc-Enabled Server to run Azure Monitor Agent on Raspberry Pi 4 running ubuntu 22.04
and I receive the following error when running the installation script generated on Azure.
"
E: Unable to locate package azcmagent
/home/pi/install_linux_azcmagent.sh: error installing azcmagent (exit code: 100). See 'apt' command logs for more information.
sudo: azcmagent: command not found
"

I am able to install the Arc-Enabled Server to run Ubuntu 22.04, which has the x86_64 architecture. So I am aware that is a platform issue. However I am confused by the fact per Azure Monitor Agent documentation.:
![image](https://github.com/microsoft/linux-package-repositories/assets/101602307/6686e158-68fc-4097-a05b-104a8ad17f1a)
Ubuntu 22 on ARM64 should be supported.

**When did the issue occur?**
The issue is relevant as of 06.03.2024.

**Comment by edyoung** [comment]
There are two separate packages, Arc/Azcmagent and AMA. AMA supports ARM64, for example when installed on an ARM64 Azure VM. Arc does not yet have ARM64 support, but we're working on it.
