### ISSUE TITLE
403 on https://packages.microsoft.com/ubuntu/22.04/prod

### ISSUE THREAD

**Issue by SMAVRillo** [microsoft/linux-package-repositories#119]
**Describe the issue**
Suddenly getting 403 on `packages.microsoft.com` within Github Actions Workflow:

```
Err:12 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 mssql-tools18 amd64 18.2.1.1-1 403  Forbidden [IP: *.*.*.* 443]
```

**When did the issue occur?**
This step within our Github Actions Workflow installs the prerequisites we need for setting up our automated testing, we're installing `mssql-tools18` to execute MSSQL commands from CLI

```
      - name: Install Prerequisites
        run: |
          sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
          curl -sSL -O https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          rm packages-microsoft-prod.deb
          sudo apt-get update && sudo apt-get install -y mssql-tools18 unixodbc-dev libonig-dev libmcrypt-dev mcrypt liblz4-dev liblzf-dev libzstd-dev gconf-service libstdc++6 ca-certificates libnss3 lsb-release wget libgbm-dev
```

**Steps to Reproduce**

**Actual Result**
```
Err:12 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 mssql-tools18 amd64 18.2.1.1-1 403  Forbidden [IP: *.*.*.* 443]
```

```
E: Failed to fetch https://pmc-geofence.trafficmanager.net/ubuntu/22.04/prod/pool/main/m/mssql-tools18/mssql-tools18_18.2.1.1-1_amd64.deb?geofence=true  403  Forbidden [IP: *.*.*.* 443]
```

**Expected Result**

`mssql-tools18` successfully installs and continues with the rest of out workflow.

**Screenshots**

**Additional context**

**Comment by ferrouswheel** [comment]
We are also experiencing this in our Github Actions Workflow.

**Comment by NzKyle** [comment]
I too am experiencing these issues today. 

It's happening from my local machine, GitHub Actions and ADO pipelines.

**Comment by jschroe212** [comment]
+1

**Comment by JohnKeippel** [comment]
Though I suspect this is all very related, don't want to just be a "+1":

Get:1 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 msodbcsql17 amd64 17.10.5.1-1 [749 kB]
Err:2 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 mssql-tools amd64 17.10.1.1-1
  403  Forbidden [IP: 4.155.111.140 443]
Fetched 749 kB in 1s (938 kB/s)
E: Failed to fetch https://pmc-geofence.trafficmanager.net/ubuntu/18.04/prod/pool/main/m/mssql-tools/mssql-tools_17.10.1.1-1_amd64.deb?geofence=true  403  Forbidden [IP: 4.155.111.140 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by phromo** [comment]
Also affects https://packages.microsoft.com/ubuntu/22.04/mssql-server-2022/pool/main/m/mssql-server/ packages.

**Comment by mbearup** [comment]
We're investigating the issue. Over the past several weeks we've updated our infrastructure, which includes a Web Application Firewall (WAF) to meet emerging security requirements. It's likely that the WAF is rejecting some requests based on its ruleset. We're looking into mitigation now.

**Comment by SpudInNZ** [comment]
Just chiming in here, this has blocked all our deployments, including production. I hope you can resolve this quickly @mbearup and please reach out to me if we can help with testing.

**Comment by mbearup** [comment]
This should now be mitigated. There was an issue with the WAF rules preventing download of these files. If anyone is still seeing this symptom let us know.

**Comment by JohnKeippel** [comment]
That resolved the issue for us. Thanks!

**Comment by vbadrike-godaddy** [comment]
@mbearup I am seeing a similar issue https://github.com/microsoft/linux-package-repositories/issues/120

**Comment by dben-gaig** [comment]
@mbearup I'm still seeing this issue on https://packages.microsoft.com/config/rhel/8/mssql-server-2019

`Status code: 403 for https://pmc-geofence.trafficmanager.net/rhel/8/mssql-server-2019/Packages/m/mssql-server-15.0.4355.3-4.x86_64.rpm?geofence=true`

Let me know if you want me to create a new issue for this package.

**Comment by dben-gaig** [comment]
Yep looks like a firewall issue on our side to the new domain, we'll update that. I'll follow up if I have any other issues with this.

Thanks @mbearup
