### ISSUE TITLE
403 on https://packages.microsoft.com/debian/10/prod

### ISSUE THREAD

**Issue by vbadrike-godaddy** [microsoft/linux-package-repositories#120]
**Describe the issue**
Getting 403 on packages.microsoft.com within Github Actions Workflow:
`Err:1 https://packages.microsoft.com/debian/10/prod buster/main amd64 mssql-tools amd64 17.10.1.1-1  403  Forbidden [IP: *.*.*.* 443]`
`E: Failed to fetch https://pmc-geofence.trafficmanager.net/debian/10/prod/pool/main/m/mssql-tools/mssql-tools_17.10.1.1-1_amd64.deb?geofence=true  403  Forbidden [IP: *.*.*.* 443]`
**When did the issue occur?**
We have a step within our github actions workflow which installs `mssql-tools`
**Steps to Reproduce**
We are trying to install odbc driver using this steps https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16&tabs=debian18-install%2Calpine17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline 

**Actual Result**
`Err:1 https://packages.microsoft.com/debian/10/prod buster/main amd64 mssql-tools amd64 17.10.1.1-1 403  Forbidden [IP: *.*.*.* 443]`
`E: Failed to fetch https://pmc-geofence.trafficmanager.net/debian/10/prod/pool/main/m/mssql-tools/mssql-tools_17.10.1.1-1_amd64.deb?geofence=true  403  Forbidden [IP: *.*.*.* 443]`
**Expected Result**
`mssql-tools` is successfully installed and continues with the rest of our workflow
**Screenshots**
**Additional context**

**Comment by Moustafa-Moustafa** [comment]
We started using an updated Web Application Firewall (WAF) to improve on the security of our services. The new WAF was blocking some legit requests including the one in this issue. 
We have mitigated this issue as of 30 mins ago. Can you please try again and let us know if you continue to see the issues?

**Comment by vbadrike-godaddy** [comment]
Its working now thanks for looking into it @Moustafa-Moustafa
