### ISSUE TITLE
MS edge repo InRelease file checksum mismatch on most nodes

### ISSUE THREAD

**Issue by GirtsD-WS** [microsoft/linux-package-repositories#123]
**Describe the issue**
MS edge repo InRelease file sha256 hash mismatch to referenced file

**When did the issue occur?**
Started development on 25th of march and the issue was already there

**If applicable, what package did you attempt to install, and from which repo?**
Trying to mirror and update from Microsoft edge repository

**Steps to Reproduce**
Using aptly software (on GH-runner) try to update from the repo after creating a mirror of the repo.
`aptly mirror create microsoft-edge https://packages.microsoft.com/repos/edge stable main`
`aptly mirror update microsoft-edge`

**Actual Result**
Downloading https://packages.microsoft.com/repos/edge/dists/stable/InRelease...
Success downloading https://packages.microsoft.com/repos/edge/dists/stable/InRelease
Downloading & parsing package files...
Downloading https://packages.microsoft.com/repos/edge/dists/stable/main/binary-all/Packages.gz...
Error downloading https://packages.microsoft.com/repos/edge/dists/stable/main/binary-all/Packages.gz: https://packages.microsoft.com/repos/edge/dists/stable/main/binary-all/Packages.gz: sha256 hash mismatch "4f9d5f01e0ee0b2d12d982f3a331e1fb63702cf6234ae09e3fc451c99448d05c" != "1bc8a5707c8559f9e3ffd10638a78f9f06f6ccdc269e2fd3a20d4e7f169f9d21" retrying...

**Expected Result**
Download of all packages in repo

**Additional context**
This issue occurs when using gh runners provided by github both on ubuntu-latest and ubuntu-22.04-4core. The InRelease file responsible is not wrong on all nodes, but only on some. When downloading the file manually it has the correct checksum in it. When downloading the file on gh-runner it fails 9/10 times occasionally hitting a node that houses the repo with the correct file

**Comment by daviddavis** [comment]
Thank you for the bug report. I've refreshed the cache. We've switched to serving packages from a CDN and we're still working on better strategies to prevent the cache from getting out of sync like this so it won't happen again in the future. Let us know if you're still hitting this issue or run into any other problems.
