### ISSUE TITLE
Problem with "dotnet-sdk-8.0_8.0.203-1_amd64.deb" package

### ISSUE THREAD

**Issue by FrancescoPaoloL** [microsoft/linux-package-repositories#124]
**Describe the issue**
There is a problem with this packages
https://packages.microsoft.com/debian/12/prod/pool/main/d/dotnet-sdk-8.0/dotnet-sdk-8.0_8.0.203-1_amd64.deb

**When did the issue occur?**
When I try to upgrade my debian os

**If applicable, what package did you attempt to install, and from which repo?**
https://packages.microsoft.com/debian/12/prod/pool/main/d/dotnet-sdk-8.0/

**Steps to Reproduce**
sudo apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  linux-headers-amd64 linux-image-amd64
The following packages will be upgraded:
  dotnet-sdk-8.0
1 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Need to get 110 MB of archives.
After this operation, 3,072 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 https://packages.microsoft.com/debian/12/prod bookworm/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1 [110 MB]
Ign:1 https://packages.microsoft.com/debian/12/prod bookworm/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1
Ign:1 https://packages.microsoft.com/debian/12/prod bookworm/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1
Ign:1 https://packages.microsoft.com/debian/12/prod bookworm/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1
Err:1 https://packages.microsoft.com/debian/12/prod bookworm/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1
  Error reading from server. Remote end closed connection [IP: 13.107.246.43 443]
E: Failed to fetch https://packages.microsoft.com/debian/12/prod/pool/main/d/dotnet-sdk-8.0/dotnet-sdk-8.0_8.0.203-1_amd64.deb  Error reading from server. Remote end closed connection [IP: 13.107.246.43 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

I've tried to clean apt etc; I've tried to download it manually via browser, but is there a problem because "the source file could not be read"

**Actual Result**
No new dotnet-sdk-8.0 installed

**Expected Result**
That packages it will be downloadable,

**Screenshots**
See the result if I try to download it manually via browser
![Screenshot_2024-03-27_06-11-09](https://github.com/microsoft/linux-package-repositories/assets/47259713/f7393ccc-e175-4989-9045-88f9a1cb4f9b)

**Additional context**
This is my OS:

- OS: Debian GNU/Linux 12 (bookworm) x86_64 
- Kernel: 6.1.0-16-amd64 
- Shell: bash 5.2.15 
- Terminal: xfce4-terminal 

Let me know if you want other info about this issue.

Francesco

**Comment by jasonzio** [comment]
I have no trouble fetching that file via browser; most recent attempt at 2024-03-27 0642UTC.

This may seem like a dumb question but - do you have enough free disk space to download the package and unpack it?

**Comment by FrancescoPaoloL** [comment]
> I have no trouble fetching that file via browser; most recent attempt at 2024-03-27 0642UTC.
> 
> This may seem like a dumb question but - do you have enough free disk space to download the package and unpack it?

Ciao jasonzio and thanks for your comment.
So, I have this situation in the OS disk (where is the Downloads folder):
83.7 GiB used (9%) | 830.7 GiB free (91%)
I suppose I have enough space.
I've tried another disk: same result.

However I've tried to use wget:

--2024-03-27 07:55:09--  https://packages.microsoft.com/debian/12/prod/pool/main/d/dotnet-sdk-8.0/dotnet-sdk-8.0_8.0.203-1_amd64.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 13.107.246.43, 13.107.213.43, 2620:1ec:bdf::43, ...
Connecting to packages.microsoft.com (packages.microsoft.com)|13.107.246.43|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 110251086 (105M) [application/octet-stream]
Saving to: ‘dotnet-sdk-8.0_8.0.203-1_amd64.deb’

dotnet-sdk-8.0_8.0.203-1_amd64.deb               30%[==============================>                                                                       ]  32.00M  22.6MB/s    in 1.4s    

2024-03-27 07:55:11 (22.6 MB/s) - Connection closed at byte 33554432. Retrying.

etcetera

**Comment by Klaas-** [comment]
do you have a transparent corporate proxy?

**Comment by FrancescoPaoloL** [comment]
> do you have a transparent corporate proxy?

Ciao Klaas,
No, as far as I know. Is there a way to verify it in Debian?

**Comment by Peperud** [comment]
[Similar for me](https://github.com/microsoft/linux-package-repositories/issues/48#issuecomment-2027697894). 
With or without a corp proxy (Ubuntu in WSL2 behind a corp proxy and KDE Neon without proxy).
I gave up and manually downloaded and installed the package.

**Comment by FrancescoPaoloL** [comment]
> [Similar for me](https://github.com/microsoft/linux-package-repositories/issues/48#issuecomment-2027697894). With or without a corp proxy (Ubuntu in WSL2 behind a corp proxy and KDE Neon without proxy). I gave up and manually downloaded and installed the package.

Ciao Paperud,

There has been no progress with the issue. So I have done the same, installing it manually.
However, the issue remains. What should I do? Should I close it, however?

Francesco

**Comment by daviddavis** [comment]
I have manually cleared the affected package paths from our cache so the problem should be fixed. Please try again and let me know if it works.

We also have a fix going out which should prevent corrupted packages from ending up in the cache in the future.
