### ISSUE TITLE
Installation AZURE ARC Debian GNU/Linux 12 (64-bit)

### ISSUE THREAD

**Issue by Valentin388** [microsoft/linux-package-repositories#128]
**Describe the issue**
When I want to install the ARC agent on a Debian GNU/Linux 12 (64-bit) machine, I get this error message :
 bash ~/install_linux_azcmagent.sh;
Using 'curl' for downloads
Total physical memory: 16376580 kB
Platform type:  x86_64:Linux
Retrieving distro info from /etc/os-release...
Configuring for Debian 12...
E: Des valeurs entrant en conflit ont été renseignées pour l'option Signed-By à propos de la source https://packages.microsoft.com/debian/12/prod/ bookworm: /usr/share/keyrings/microsoft-prod.gpg !=
E: La liste des sources ne peut être lue.
E: Des valeurs entrant en conflit ont été renseignées pour l'option Signed-By à propos de la source https://packages.microsoft.com/debian/12/prod/ bookworm: /usr/share/keyrings/microsoft-prod.gpg !=
E: La liste des sources ne peut être lue.

E: Des valeurs entrant en conflit ont été renseignées pour l'option Signed-By à propos de la source https://packages.microsoft.com/debian/12/prod/ bookworm: /usr/share/keyrings/microsoft-prod.gpg !=
E: La liste des sources ne peut être lue.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4304  100  4304    0     0  76088      0 --:--:-- --:--:-- --:--:-- 76857
(Lecture de la base de données... 41699 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../packages-microsoft-prod.deb ...
Dépaquetage de packages-microsoft-prod (1.1-debian12) sur (1.1-debian12) ...
Paramétrage de packages-microsoft-prod (1.1-debian12) ...
File /usr/share/keyrings/microsoft-prod.gpg is missing. Installing...
E: Des valeurs entrant en conflit ont été renseignées pour l'option Signed-By à propos de la source https://packages.microsoft.com/debian/12/prod/ bookworm: /usr/share/keyrings/microsoft-prod.gpg !=
E: La liste des sources ne peut être lue.
E: Des valeurs entrant en conflit ont été renseignées pour l'option Signed-By à propos de la source https://packages.microsoft.com/debian/12/prod/ bookworm: /usr/share/keyrings/microsoft-prod.gpg !=
E: La liste des sources ne peut être lue.
/root/install_linux_azcmagent.sh: error installing azcmagent (exit code: 100). See 'apt' command logs for more information.

**When did the issue occur?**

**If applicable, what package did you attempt to install, and from which repo?**

**Steps to Reproduce**

**Actual Result**

**Expected Result**

**Screenshots**
![image](https://github.com/microsoft/linux-package-repositories/assets/166416059/b62f9318-4c93-41d5-98e4-6232e94471b5)

**Additional context**
I try this command to get new keyring  : wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
rm -f packages.microsoft.gpg

**Comment by mbearup** [comment]
@Valentin388 With Debian 12/bookworm, we switched to using apt's "signed-by" directive to comply with Debian policy.
The [.list ](https://packages.microsoft.com/config/debian/12/prod.list) file assumes the pubkey is installed to `/usr/share/keyrings/microsoft-prod.gpg` and the [installer](https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb) should install the key to the correct location.
- Could you confirm that the pubkey is installed to `/usr/share/keyrings/microsoft-prod.gpg`?
- Could you check the contents of your .list file under `/etc/apt/sources.list.d/` to confirm the `signed-by` directive points to the file above?

**Comment by Valentin388** [comment]
Yes the pubkey is installed to /usr/share/keyrings/microsoft-prod.gpg and yes the directive points to the file above?/etc/apt/sources.list.d/signed-by

We found a command to fix the problem :
curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
