### ISSUE TITLE
Slow download speeds

### ISSUE THREAD

**Issue by daviddavis** [microsoft/linux-package-repositories#13]
Seeing slow download speeds when attempting to download a package:

```
$ curl https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.30.0-1\~bullseye_all.deb --remote-name
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  2 63.4M    2 1375k    0     0   112k      0  0:09:35  0:00:12  0:09:23  117k
```

Compare this to a package from deb.debian.org:

```
$ curl https://deb.debian.org/debian/pool/main/a/azure-cli/azure-cli_2.18.0.orig.tar.gz --remote-name
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 80 47.9M   80 38.5M    0     0  9736k      0  0:00:05  0:00:04  0:00:01 9733k
```

**Comment by NoahStahl** [comment]
Noting that I see slow downloads also, but on Windows. So this isn't necessarily related to OS, perhaps a CDN/hosting issue generally. (anecdotally, I'm downloading in Austin TX)

**Comment by jon-dez** [comment]
Some with me, 150 kbps download speeds on gigabit internet. It happens nearly every time I try to update visual studio code for ubuntu 22.04. 
(Philadelphia, PA if it helps track down cdn issues)

**Comment by zakeryooo** [comment]
Happening for me too, servers in Helsinki, Nuremberg & London all downloading at < 200 kB/s from packages.microsoft.com

**Comment by abjoseph** [comment]
Happening for me as well...current location: Fairfax, VA. 600Mbps connection downloading @ < 150 kB/s

**Comment by punarjit-singh** [comment]
Happening for our team as well:

```
Get:1 https://download.docker.com/linux/ubuntu focal InRelease [57.7 kB]
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]      
Get:3 https://packages.cloud.google.com/apt cloud-sdk InRelease [6,751 B]      
Get:4 https://download.docker.com/linux/ubuntu focal/stable amd64 Packages [19.6 kB]
Hit:5 http://archive.ubuntu.com/ubuntu focal InRelease                         
Get:6 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease [23.8 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:8 https://packages.cloud.google.com/apt cloud-sdk/main amd64 Packages [295 kB]
Get:9 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [1,401 kB]
Get:10 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2,035 kB]
Get:11 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [884 kB]
Get:12 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [27.5 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]     
Get:14 http://ppa.launchpad.net/git-core/ppa/ubuntu focal/main amd64 Packages [3,171 B]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [1,513 kB]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [30.2 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,161 kB]
Get:18 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2,483 kB]
Get:19 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [54.2 kB]
Get:20 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [27.1 kB]
Fetched 10.4 MB in 1s (8,267 kB/s)                          
Reading package lists... Done
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 98945 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_2.0.9_all.deb ...
Unpacking apt-transport-https (2.0.9) over (2.0.6) ...
Setting up apt-transport-https (2.0.9) ...
deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ focal main
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   983  100   983    0     0   3681      0 --:--:-- --:--:-- --:--:--  3681
OK
Hit:1 https://download.docker.com/linux/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease               
Hit:3 https://packages.cloud.google.com/apt cloud-sdk InRelease                
Hit:4 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease             
Hit:5 http://archive.ubuntu.com/ubuntu focal InRelease                         
Hit:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease               
Get:7 https://packages.microsoft.com/repos/azure-cli focal InRelease [10.4 kB]
Hit:8 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Get:9 https://packages.microsoft.com/repos/azure-cli focal/main amd64 Packages [9,289 B]
Fetched 19.7 kB in 1s (28.2 kB/s)     
Reading package lists... Done

Too long with no output (exceeded 10m0s): context deadline exceeded
```

**Comment by jean-paullizotte** [comment]
It's been two days, any ETA on this issue?

**Comment by mbearup** [comment]
Apologies all for the disruption. The package mirrors were exceeding their network egress limit of 4Gbps per VM. We've upgraded the VM SKUs, which are now pushing an average of 6Gbps egress per VM. Speed tests are showing download speeds of ~40MBps.

**Comment by jean-paullizotte** [comment]
That was it? 
Shouldn't there be some kind of monitoring to alert you when this happens?
Nevertheless thank you for addressing this.

**Comment by NoahStahl** [comment]
Interesting that this is served from VMs, seems like a typical CDN use case... Thanks for the update!

**Comment by davidecavestro** [comment]
Still experiencing slowdowns
![image](https://user-images.githubusercontent.com/447917/181917283-75d6f417-15eb-44ea-baf5-1c9cd88f78be.png)

**Comment by jean-paullizotte** [comment]
> Still experiencing slowdowns ![image](https://user-images.githubusercontent.com/447917/181917326-db85ddfd-7fe6-4ce6-9785-fc9f9eac140c.png) stuck between 20-40 kB/s though the speedtest is ok

This is what I get pretty consistently, seems okay here (35/40 mb/sec) maybe it was a temporary thing?
![image](https://user-images.githubusercontent.com/36302005/182023414-78230caf-5a9c-481b-bbef-9bc42f6f125c.png)

**Comment by muzuiget** [comment]
`packages.microsoft.com` is super slow even I use a US cloud server as proxy, when update `edge` and `vscode` package, it take me half an hour sometime.

**Comment by victor-borges** [comment]
Seems like this problem resurfaced in the past few days, I'm currently stuck with download speeds of 60~80 kB/s
![image](https://user-images.githubusercontent.com/46226318/201540721-348beede-5ac4-4baa-935f-99b93dc02087.png)

**Comment by muzuiget** [comment]
@mbearup I am live in China, but it does't matter, I access the `packages.microsoft.com` through VPN (an US private proxy server). 

I download packages from other repos also fast enough, like `download.docker.com`, `mirrors.rpmfusion.org`, `dl.google.com`, it has 1MB/s at least. 

But `packages.microsoft.com` usually only has 50KB/s.

Here is the DNS I am using:

```
$ nslookup packages.microsoft.com 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
packages.microsoft.com  canonical name = apt-geofence-parent.trafficmanager.net.
apt-geofence-parent.trafficmanager.net  canonical name = csd-apt-wus-d-2.westus.cloudapp.azure.com.
Name:   csd-apt-wus-d-2.westus.cloudapp.azure.com
Address: 13.93.224.173
```

**Comment by victor-borges** [comment]
@mbearup yes, I am accessing from Brazil, no VPN or proxy involved in my case

```
$ nslookup packages.microsoft.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
packages.microsoft.com	canonical name = apt-geofence-parent.trafficmanager.net.
apt-geofence-parent.trafficmanager.net	canonical name = csd-apt-eus-d-3.eastus.cloudapp.azure.com.
Name:	csd-apt-eus-d-3.eastus.cloudapp.azure.com
Address: 13.90.56.68
```

**Comment by pkarakal** [comment]
this is still an issue. every time I try to update the packages every microsoft repo seems to be stuck at 30-60Kbps and I have to end up skipping them. Please forward packages.microsoft.com to cdns or increase the instances/instance size on azure. This has been happening for over a year and almost every time a new package version is released and it's getting tiring

**Comment by yoyofreeman** [comment]
Yes, still no improvement so far.

```shell
$ dig packages.microsoft.com
;; communications error to 127.0.0.1#53: connection refused
;; communications error to 127.0.0.1#53: connection refused
;; communications error to 127.0.0.1#53: connection refused

; <<>> DiG 9.18.12-0ubuntu0.22.04.2-Ubuntu <<>> packages.microsoft.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46773
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 6, ADDITIONAL: 8

;; QUESTION SECTION:
;packages.microsoft.com.                IN      A

;; ANSWER SECTION:
packages.microsoft.com. 2916    IN      CNAME   apt-geofence-parent.trafficmanager.net.
apt-geofence-parent.trafficmanager.net. 600 IN CNAME csd-apt-eas-d-3.eastasia.cloudapp.azure.com.
csd-apt-eas-d-3.eastasia.cloudapp.azure.com. 600 IN A 23.99.120.248

;; AUTHORITY SECTION:
eastasia.cloudapp.azure.com. 283 IN     NS      ns11-05.azure-dns.org.
eastasia.cloudapp.azure.com. 283 IN     NS      ns10-05.azure-dns.net.
eastasia.cloudapp.azure.com. 283 IN     NS      ns12-05.azure-dns.info.
eastasia.cloudapp.azure.com. 283 IN     NS      ns1-05.azure-dns.com.
eastasia.cloudapp.azure.com. 283 IN     NS      ns9-05.azure-dns.com.
eastasia.cloudapp.azure.com. 283 IN     NS      ns2-05.azure-dns.net.

;; ADDITIONAL SECTION:
ns1-05.azure-dns.com.   2637    IN      A       13.107.236.5
ns2-05.azure-dns.net.   390     IN      A       150.171.21.5
ns11-05.azure-dns.org.  84      IN      A       13.107.222.5
ns12-05.azure-dns.info. 2616    IN      A       13.107.206.5
ns10-05.azure-dns.net.  471     IN      A       150.171.16.5
ns9-05.azure-dns.com.   2081    IN      A       150.171.10.5
ns1-05.azure-dns.com.   2640    IN      AAAA    2603:1061:0:700::5
ns2-05.azure-dns.net.   2593    IN      AAAA    2620:1ec:8ec:700::5

;; Query time: 8 msec
;; SERVER: 61.134.1.4#53(61.134.1.4) (UDP)
;; WHEN: Wed Sep 13 00:50:38 CST 2023
;; MSG SIZE  rcvd: 490
```
The download speed is 20kib/s, and it usually takes more than 50 minutes for vscode to update.

**Comment by yaayes** [comment]
This issue pop up again lately, I can't update VS Code and Edge, even though my internet is very fast!

![Screenshot from 2023-10-05 11-13-49](https://github.com/microsoft/linux-package-repositories/assets/20878658/51c803ab-98a8-4be1-9899-346ba73085d8)

![Screenshot from 2023-10-05 11-15-50](https://github.com/microsoft/linux-package-repositories/assets/20878658/9db4c0af-88eb-40c2-94cc-3143e3a741eb)

**Comment by boussouira** [comment]
Happens again lately, seems like MS is throttling, i had to use different proxy just to update vscode, each time apt get throttled after a few seconds only  

This bring back memory if old times when we had Kb/s internet speed  
```
Get:1 http://packages.microsoft.com/repos/code stable/main amd64 code amd64 1.83.0-1696350811 [95.7 MB]  
[1 code 35.7 MB/95.7 MB 37%]  38.2 kB/s ETA: 26min 10s

```

![image](https://github.com/microsoft/linux-package-repositories/assets/1050218/c32cbf4c-591e-4388-8e1d-db6e2afd03ab)

**Comment by acheng-01** [comment]
Commenting here as well - we are aware that the slow download speeds pointed out here are persisting and are actively working to mitigate this issue. For any further questions or concerns, please refer to #50 as the new main thread on this. We will do our best to post updates there on the status of the fix.

Thank you for your patience.
