### ISSUE TITLE
Missing https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease

### ISSUE THREAD

**Issue by dmatlak** [microsoft/linux-package-repositories#131]
**Describe the issue**
Package https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease missing

**When did the issue occur?**
Today, since 2024-04-24 10:09:00 GMT+2

**If applicable, what package did you attempt to install, and from which repo?**
prod/dists/jammy

**Steps to Reproduce**
https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease

**Actual Result**
nothing downloaded

**Expected Result**
should download something

**Comment by marceltschoppch** [comment]
Sames issue here, the "InRelease" file is empty

**Comment by marceltschoppch** [comment]
See https://github.com/microsoft/linux-package-repositories/issues/130

**Comment by dmatlak** [comment]
ok, closed
