### ISSUE TITLE
Ubuntu 24.04 Package libicu Broken Dependency

### ISSUE THREAD

**Issue by aaronsheldon** [microsoft/linux-package-repositories#135]
**Describe the issue**
Ubuntu 24.04 is on version 74 of libicu (unicode for C++), while packages in the Microsoft repository requires version 72, or older. Neither PowerShell nor DotNet are installable from the Microsoft repository.

**When did the issue occur?**
Starts with Ubuntu 24.04. Tried unsuccessfully to install DotNet 6 & 7, and PowerShell 7.4 using the Microsoft Package Repository.

**Steps to Reproduce**
1. Upgrade to Ubuntu 24.04.
2. Download and run the Microsoft package for Ubuntu 24.04 to configure the Microsoft repository.
3. Try to install DotNet 6 or 7, or PowerShell 7.4 packages through apt or synaptic.

**Actual Result**
Fails to install, reporting that the dependency on libicu 72 or lower cannot be satisfied.

**Expected Result**
All packages should install and run with libicu 74.

Sigh...disappointing.

```[tasklist]
### Tasks
```

**Comment by sdherr** [comment]
Hi @aaronsheldon, these Issues are only monitored by the team that maintains the packages.microsoft.com infrastructure, however I have sent an internal notification to the .NET team. Can you please clarify where you're pulling PowerShell from? As far as I'm aware PowerShell has not been published for 24.04 yet.

**Comment by aaronsheldon** [comment]
Thank you @sdherr. I'm following the usual instructions from [Learn Microsoft](https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4). This uses the standard repository setup package `packages-microsoft-prod.deb`. In my case from the [Ubuntu 24.04 directory](https://packages.microsoft.com/config/ubuntu/24.04/). Oddly the repositoy does contain the PowerShell package, along with DotNet 6 & 7.

Granted I may have jumped the gun a bit in trying to get these to install on Ubuntu 24.04. It has only been a week or so since Canonical unlocked the 24.04 upgrade to the general public.

**Comment by sdherr** [comment]
Ah okay, it looks like an Issue for that already exists on the [PowerShell repo](https://github.com/PowerShell/PowerShell/issues/23197). I suggest you follow that for PowerShell updates, although I suspect it's simply as you say: they haven't rebuilt it for 24.04 yet. These .NET packages though have been released to our 24.04 repo though, so they _should_ work. Hopefully the .NET team can chime in here soon.

**Comment by ashnaga** [comment]
On 24.04, use Ubuntu feed for .NET installation - [Install Doc](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-install?pivots=os-linux-ubuntu-2404&tabs=dotnet8#ubuntu-2404)

[Blog post](https://devblogs.microsoft.com/dotnet/whats-new-for-dotnet-in-ubuntu-2404/) describing more details and have detailed instructions.

**Comment by sdherr** [comment]
Hi @ashnaga, I'm afraid your documentation is incorrect, you are in fact shipping the 6.0 and 7.0 packages in Microsoft's Ubuntu 24.04 repo:
https://packages.microsoft.com/ubuntu/24.04/prod/pool/main/d/

If that's not intended / desired then you need to remove them so that subscribers to that repo won't install broken packages.
