### ISSUE TITLE
Permission to access 'https://packages.microsoft.com/sles/12/prod/media.1/media' denied.

### ISSUE THREAD

**Issue by jvz1984** [microsoft/linux-package-repositories#136]
**Describe the issue**
Permission to access 'https://packages.microsoft.com/sles/12/prod/media.1/media' denied. when trying to refresh the repo. On multiple machines. Firewall and proxy allow the traffic, this is confirmed. Feels to me like web server is configured wrong or there's a reference to this path somewhere in the repo.

**When did the issue occur?**
Noticed it yesterday. Don't know how long it's been around.

**If applicable, what package did you attempt to install, and from which repo?**
Azure Arc agent. I think they are: gcad.service and extd.service. I have issues with these too but that's another story.

**Steps to Reproduce**
zypper ref

**Actual Result**
Repository 'SLES12-SP5-Pool' is up to date.
Repository 'SLES12-SP5-Updates' is up to date.
Permission to access 'https://packages.microsoft.com/sles/12/prod/media.1/media' denied.
Abort, retry, ignore? [a/r/i/...? shows all options] (a): a

**Expected Result**
Repository 'packages-microsoft-com-prod' is up to date.

**Screenshots**
![image](https://github.com/microsoft/linux-package-repositories/assets/18534805/5f97fd2a-d485-4c01-9917-665a4a40a05b)
![image](https://github.com/microsoft/linux-package-repositories/assets/18534805/de061c44-ad9f-4c2c-8940-96ac107abb9e)

**Additional context**
Sles15 repo works without issue on SLES15 VM's. Issue seems only in sles12 repo.

Content of /etc/zypp/repos.d/microsoft-prod.repo
![image](https://github.com/microsoft/linux-package-repositories/assets/18534805/005fac70-83fb-433e-9488-82d97919fff7)

**Comment by Moustafa-Moustafa** [comment]
We have added some new restrictions on the allowed paths that we server, and parts of the path you had issue with was included by mistake. This issue has now been resolved, please try again and let us know if you see any other issues.

**Comment by jvz1984** [comment]
> We have added some new restrictions on the allowed paths that we server, and parts of the path you had issue with was included by mistake. This issue has now been resolved, please try again and let us know if you see any other issues.

`Repository 'SLES12-SP5-Pool' is up to date.
Repository 'SLES12-SP5-Updates' is up to date.
Repository 'packages-microsoft-com-prod' is up to date.
All repositories have been refreshed.

S | Repository                  | Name                               | Current Version          | Available Version  | Arch
--+-----------------------------+------------------------------------+--------------------------+--------------------+-------
v | packages-microsoft-com-prod | azcmagent                          | 1.36.02501-1252          | 1.42.02699-1576    | x86_64
v | packages-microsoft-com-prod | omi                                | 1.7.3-0                  | 1.9.0-0            | x86_64
v | packages-microsoft-com-prod | scx                                | 1.7.3-0                  | 1.9.0-0            | x86_64`

That's looking much better. Thanks.
