### ISSUE TITLE
Ubuntu 22.04 - libunbound8-1.13.1 not found

### ISSUE THREAD

**Issue by mblackgeo** [microsoft/linux-package-repositories#137]
**Describe the issue**
A github actions pipeline is failing on installation with the following error.

```
E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/main/u/unbound/libunbound8_1.13.1-1ubuntu5.4_amd64.deb  
404  Not Found [IP: 52.147.219.192 80]
```

**When did the issue occur?**
First observed on May 29th

**If applicable, what package did you attempt to install, and from which repo?**
`libunbound8`

**Steps to Reproduce**
`apt install libunbound8` (on Github actions 22.04 runner)

**Actual Result**
```
E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/main/u/unbound/libunbound8_1.13.1-1ubuntu5.4_amd64.deb  
404  Not Found [IP: 52.147.219.192 80]
```

**Expected Result**
Installs fine on Ubuntu 22.04 with default apt mirrors (outside of GHA runners)

Not sure if this is correct place to raise this ticket, please close if this is not correct, thanks

**Comment by mbearup** [comment]
@mblackgeo sorry to hear about your experience with GHA runners. Unfortunately, this instance is exclusively for supporting packages.microsoft.com. So, unless this package is being installed from packages.microsoft.com, we're unable to provide support here.
