### ISSUE TITLE
504 Gateway Time-out on packages.microsoft.com

### ISSUE THREAD

**Issue by timd73** [microsoft/linux-package-repositories#138]
**Describe the issue**
504 errors on PMC

**When did the issue occur?**
Sun Jun 9, all day.

**If applicable, what package did you attempt to install, and from which repo?**
https://packages.microsoft.com/rhel/9/prod/msodbcsql18-18.1.1.1-1.x86_64.rpm
https://packages.microsoft.com/rhel/9/prod/mssql-tools18-18.1.1.1-1.x86_64.rpm

**Steps to Reproduce**
```
wget "https://packages.microsoft.com/rhel/9/prod/msodbcsql18-18.1.1.1-1.x86_64.rpm"
--2024-06-09 17:29:17--  https://packages.microsoft.com/rhel/9/prod/msodbcsql18-18.1.1.1-1.x86_64.rpm
Resolving packages.microsoft.com (packages.microsoft.com)... 13.107.246.43
Connecting to packages.microsoft.com (packages.microsoft.com)|13.107.246.43|:443... connected.
HTTP request sent, awaiting response... 504 Gateway Time-out
Retrying.
```

**NOTE:** Intermittent - it sometimes succeeds, especially when run from GitHub actions, but it fails frequently too. From my laptop, it always fails.

**Actual Result**
`504 Gateway Time-out`

**Expected Result**
`200 OK` and file downloaded

**Comment by mbearup** [comment]
@timd73 there is currently an outage affecting packages.microsoft.com. Our central infrastructure is unable to pull container images that are used for central services. We're working urgently to resolve the issue,

**Comment by mbearup** [comment]
packages.microsoft.com service should now be restored. Let us know if you continue to see issues.

**Comment by timd73** [comment]
@mbearup  right now it looks solved - I'll let you know if it recurs.
Thanks!
