### ISSUE TITLE
Not able to download Microsoft Teams Linux

### ISSUE THREAD

**Issue by ajeetshah** [microsoft/linux-package-repositories#148]
Steps to reproduce the issue:

1. Go to https://www.microsoft.com/en-us/microsoft-teams/download-app
2. It shows button to download teams app for linux:
![image](https://github.com/microsoft/linux-package-repositories/assets/5670016/72d47515-e4e9-4395-baba-e7bc7438d2cb)
3. On click of the above button, it takes me to https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.5.00.23861_amd64.deb which returns *error 404*.
![image](https://github.com/microsoft/linux-package-repositories/assets/5670016/feda7578-93a6-4733-8891-99f21cdec635)

**Comment by mbearup** [comment]
The Teams client for Linux was deprecated in 2022, and replaced with a Progressive Web App (PWA). We'll reach out to the product team to ensure docs are updated.
