### ISSUE TITLE
packages-microsoft-prod-1.1-1.noarch missing powershell

### ISSUE THREAD

**Issue by mpain-icims** [microsoft/linux-package-repositories#150]
I am using Amazon Linux 2023 and have tried this on latest fedora as well.  Powershell is no longer available aso of 1.1-1 where it was in 1.0-1.  

yum install powershell
Repository mariadb is listed more than once in the configuration
Last metadata expiration check: 0:03:09 ago on Wed Jul 10 17:40:50 2024.
No match for argument: powershell
Error: Unable to find a match: powershell

yum --disablerepo="*" --enablerepo=packages-microsoft-com-prod list available

Last metadata expiration check: 0:05:38 ago on Wed Jul 10 17:40:50 2024.
Available Packages
aspnetcore-runtime-6.0.x86_64                                                                                         6.0.32-1                                                                                          packages-microsoft-com-prod
aspnetcore-runtime-7.0.x86_64                                                                                         7.0.20-1                                                                                          packages-microsoft-com-prod
aspnetcore-runtime-8.0.x86_64                                                                                         8.0.7-1                                                                                           packages-microsoft-com-prod
aspnetcore-targeting-pack-6.0.x86_64                                                                                  6.0.32-1                                                                                          packages-microsoft-com-prod
aspnetcore-targeting-pack-7.0.x86_64                                                                                  7.0.20-1                                                                                          packages-microsoft-com-prod
aspnetcore-targeting-pack-8.0.x86_64                                                                                  8.0.7-1                                                                                           packages-microsoft-com-prod
dotnet-apphost-pack-6.0.x86_64                                                                                        6.0.32-1                                                                                          packages-microsoft-com-prod
dotnet-apphost-pack-7.0.x86_64                                                                                        7.0.20-1                                                                                          packages-microsoft-com-prod
dotnet-apphost-pack-8.0.x86_64                                                                                        8.0.7-1                                                                                           packages-microsoft-com-prod
dotnet-host.x86_64                                                                                                    8.0.7-1                                                                                           packages-microsoft-com-prod
dotnet-hostfxr-6.0.x86_64                                                                                             6.0.32-1                                                                                          packages-microsoft-com-prod
dotnet-hostfxr-7.0.x86_64                                                                                             7.0.20-1                                                                                          packages-microsoft-com-prod
dotnet-hostfxr-8.0.x86_64                                                                                             8.0.7-1                                                                                           packages-microsoft-com-prod
dotnet-runtime-6.0.x86_64                                                                                             6.0.32-1                                                                                          packages-microsoft-com-prod
dotnet-runtime-7.0.x86_64                                                                                             7.0.20-1                                                                                          packages-microsoft-com-prod
dotnet-runtime-8.0.x86_64                                                                                             8.0.7-1                                                                                           packages-microsoft-com-prod
dotnet-runtime-deps-6.0.x86_64                                                                                        6.0.32-1                                                                                          packages-microsoft-com-prod
dotnet-runtime-deps-7.0.x86_64                                                                                        7.0.20-1                                                                                          packages-microsoft-com-prod
dotnet-runtime-deps-8.0.x86_64                                                                                        8.0.7-1                                                                                           packages-microsoft-com-prod
dotnet-sdk-6.0.x86_64                                                                                                 6.0.424-1                                                                                         packages-microsoft-com-prod
dotnet-sdk-7.0.x86_64                                                                                                 7.0.410-1                                                                                         packages-microsoft-com-prod
dotnet-sdk-8.0.x86_64                                                                                                 8.0.303-1                                                                                         packages-microsoft-com-prod
dotnet-targeting-pack-6.0.x86_64                                                                                      6.0.32-1                                                                                          packages-microsoft-com-prod
dotnet-targeting-pack-7.0.x86_64                                                                                      7.0.20-1                                                                                          packages-microsoft-com-prod
dotnet-targeting-pack-8.0.x86_64                                                                                      8.0.7-1                                                                                           packages-microsoft-com-prod
mdatp.x86_64                                                                                                          101.24052.0002-1                                                                                  packages-microsoft-com-prod
mde-netfilter.x86_64                                                                                                  100.69.62-1                                                                                       packages-microsoft-com-prod
mde-netfilter-src.x86_64                                                                                              100.69.62-1                                                                                       packages-microsoft-com-prod
netstandard-targeting-pack-2.1.x86_64                                                                                 2.1.0-1                                                                                           packages-microsoft-com-prod
procdump.x86_64                                                                                                       3.3.0-0.el8                                                                                       packages-microsoft-com-prod
[

**Comment by daviddavis** [comment]
Can you file an issue in the Powershell repo? We only provide the infrastructure for serving packages and it would be up to the Powershell team to build packages for Fedora and Amazon Linux which I don't think they currently do.

https://github.com/PowerShell/PowerShell/issues
