### ISSUE TITLE
packages.microsoft.com is down ?

### ISSUE THREAD

**Issue by qfisch** [microsoft/linux-package-repositories#156]
**Describe the issue**
https://packages.microsoft.com/ is unreachable from my location (switzerland)

**When did the issue occur?**
July 30th 

**If applicable, what package did you attempt to install, and from which repo?**
mdatp

**Steps to Reproduce**
Try to run 'apt update'

**Actual Result**
can not reach apt repository

**Expected Result**
it works

**Comment by qfisch** [comment]
I hope I did not miss a status page somewhere.
I just want to make sure it is known...

**Comment by daviddavis** [comment]
Thanks, we're looking into it.

**Comment by daviddavis** [comment]
Looks like there's an Azure outage: https://azure.status.microsoft/en-us/status

**Comment by mbearup** [comment]
Our internal monitoring shows improvement in the affected regions as of ~1430UTC. However, the Azure Status page still shows network disruption in some regions, so this may not be 100% resolved. We will post more updates as they become available.

**Comment by qfisch** [comment]
It is back up in my region. Thank you for taking the time to reply to this issue.

Cheers
Q

**Comment by daviddavis** [comment]
Thanks for the update. This issue should be resolved now.
