### ISSUE TITLE
build azcmagent for Ubuntu 24.04

### ISSUE THREAD

**Issue by anthonysomerset** [microsoft/linux-package-repositories#157]
**Describe the problem you are experiencing.**

there is presently no azcmagent for Ubuntu 24.04 hosts

**Describe any possible solutions that you would like to see.**

please build and package azcmagent for Ubuntu 24.04 LTS

**Additional context.**

Upgrading an Ubuntu 22 host with azcmagent - azcmagent still works without issue - just cannot install from repo from a clean install

suspect if i manually installed the jammy/22.04 package it would work

**Comment by jasonzio** [comment]
@anthonysomerset - This repo backs up the "packages.microsoft.com" service itself, which handles package delivery. Various teams across Microsoft own the packages themselves and are responsible for the content. Some package publishers have a presence on github themselves; for those publishers, issues should be reported there. Other publishers don't have a github presence; for them, the most certain way of getting an issue resolved would be through Microsoft customer support.

That being said, we've forwarded your request to the folks who own azcmagent and asked them to respond here.

**Comment by anthonysomerset** [comment]
thanks - i did genuinely look for the right place to raise this to and couldn't find it, i am more than happy to report it in the correct place, just need to be guided where

**Comment by edyoung** [comment]
We'll be including Ubuntu 24.04 in a near-future release.

**Comment by mbearup** [comment]
I'm closing this issue, as there's no further action for the packages.microsoft.com team.
@edyoung if you could reply here once the 24.04 package is available, or share a link where customers can go for news/updates on this topic, that would be great :)

**Comment by qtdyj** [comment]
azcmagent should be available to download for Ubuntu 24.04 starting version 1.45, which was published last week.
