### ISSUE TITLE
Issues downloading Azure-CLI from packages.microsoft.com

### ISSUE THREAD

**Issue by gavinmcclay** [microsoft/linux-package-repositories#165]
**Describe the issue**
Unable to download Azure-CLI using the following URL:
https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.29.2-1~focal_all.deb
Stops at arounf 82%. Sometimes it completes but each time the file is downloaded the files sizes differ.
Tried from multiple internet connections and devices and get the same result. These internet connections are based in the UK.
There was an issue accessing Azure portal this morning that could be related but MS have reported this as being OK now.

**When did the issue occur?**
Monday 2nd September 10:00BST

**If applicable, what package did you attempt to install, and from which repo?**
https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.29.2-1~focal_all.deb

**Steps to Reproduce**
Tried from multiple internet connections and devices and get the same result. These internet connections are based in the UK.

**Actual Result**
Stops around 82%

**Expected Result**
Download of file.

**Screenshots**
Unable to provide at this time.

**Additional context**
N/A

**Comment by eorefujao** [comment]
This is a blocker. Can this be resolved quickly please?

**Comment by daviddavis** [comment]
I've purged the package from the cache. Can you try to download it again and confirm whether it's fixed?

**Comment by daviddavis** [comment]
If it's not fixed, then I need the output of `curl -v https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.29.2-1~focal_all.deb` or at least the `x-azure-ref` response header.

**Comment by gavinmcclay** [comment]
Hi, thankyou for purging from the cache, it looks like that has resolved the issue we have been facing

Thanks for your support.

**Comment by eorefujao** [comment]
> curl -v https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.29.2-1~focal_all.deb

I don't think the issue is resolved as it still broke when I tried to download from my local machine

**Comment by gavinmcclay** [comment]
@daviddavis , I managed to get it to work once but tried a second time and it didn't work.

Heres the output you wanted:

 sudo curl -v https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.29.2-1~focal_all.deb
*   Trying 2620:1ec:bdf::64:443...
*   Trying 13.107.246.64:443...
* Connected to packages.microsoft.com (13.107.246.64) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=WA; L=Redmond; O=Microsoft Corporation; CN=packages.microsoft.com
*  start date: Aug  9 18:38:34 2024 GMT
*  expire date: Aug  4 18:38:34 2025 GMT
*  subjectAltName: host "packages.microsoft.com" matched cert's "packages.microsoft.com"
*  issuer: C=US; O=Microsoft Corporation; CN=Microsoft Azure RSA TLS Issuing CA 03
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55c1c5a040)
> GET /repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.29.2-1~focal_all.deb HTTP/2
> Host: packages.microsoft.com
> user-agent: curl/7.74.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200
< date: Mon, 02 Sep 2024 16:13:05 GMT
< content-type: application/octet-stream
< content-length: 67349212
< last-modified: Tue, 25 Oct 2022 22:14:50 GMT
< etag: "0x8DAB6D6559319D2"
< x-ms-request-id: 429afc4a-d01e-0058-064c-fda416000000
< x-ms-version: 2024-08-04
< x-ms-creation-time: Tue, 25 Oct 2022 21:59:44 GMT
< x-ms-lease-status: unlocked
< x-ms-lease-state: available
< x-ms-blob-type: BlockBlob
< content-disposition: attachment;filename=azure-cli_2.29.2-1~focal_all.deb
< x-ms-server-encrypted: true
< strict-transport-security: max-age=31536000; includeSubDomains
< x-content-type-options: nosniff
< x-azure-ref: 20240902T161305Z-1748795bb76g5ngr1u2duwrar40000000ecg00000002fc9v
< cache-control: public, max-age=31536000
< x-fd-int-roxy-purgeid: 66949918
< x-cache: TCP_HIT
< x-cache-info: L1_T2
< accept-ranges: bytes
<
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
* Failure writing output to destination
* stopped the pause stream!
* Connection #0 to host packages.microsoft.com left intact

**Comment by gavinmcclay** [comment]
I have logged a wget too with verbose enabled shoing times for downloads etc. You can see it hang around 87% and doesn't really finish downloading. It will timeout eventually.
[wgetlog.txt](https://github.com/user-attachments/files/16839758/wgetlog.txt)

**Comment by daviddavis** [comment]
I need the `x-azure-ref` for a request that times out. If you're using wget, you should be able to add the `--debug` option to get this: `wget --debug https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.29.2-1~focal_all.deb`.

**Comment by gavinmcclay** [comment]
Hi @daviddavis 

x-azure-ref: 20240902T172749Z-1748795bb76g6l5q8pfu2agsks0000000ebg00000002e8n8

I do have attached the full debug also just in caase you require that.
[wgetlogdebug.txt](https://github.com/user-attachments/files/16840121/wgetlogdebug.txt)

Thanks for your help on this issue,

**Comment by daviddavis** [comment]
The request was fulfilled by the CDN and didn't hit our server, so I've tried to purge the file from cache again. I've also forwarded the issue to the CDN team. Will update once I hear back from them.

**Comment by eorefujao** [comment]
>Hopefully thus update happen before the tomorrow morning. Thanks @daviddavis

**Comment by daviddavis** [comment]
@gavinmcclay Are you still experiencing problems downloading the package? I heard back from the CDN team and they don't see any timeouts or high latencies on our end. If you're still having issues, we'd like to get a packet capture from you. I can follow up with the specific commands to run for that.

**Comment by eorefujao** [comment]
> @gavinmcclay Are you still experiencing problems downloading the package? I heard back from the CDN team and they don't see any timeouts or high latencies on our end. If you're still having issues, we'd like to get a packet capture from you. I can follow up with the specific commands to run for that.

The download issue seems to have been resolved. Thanks
