### ISSUE TITLE
   gnutls_handshake() failed: The server name sent was not recognized for https://pmc-geofence.trafficmanager.net/debian/9/prod/pool/

### ISSUE THREAD

**Issue by vineeth-sri** [microsoft/linux-package-repositories#169]
**Describe the issue**
https://pmc-geofence.trafficmanager.net/debian/9/prod/pool/ appears to be down 

#6 3.894   gnutls_handshake() failed: The server name sent was not recognized
12:09:01   #6 3.900 Fetched 1519 kB in 1s (1469 kB/s)
12:09:01   #6 3.901 E: Failed to fetch https://pmc-geofence.trafficmanager.net/debian/9/prod/pool/main/m/mssql-tools/mssql-tools_17.5.1.2-1_amd64.deb?geofence=true  gnutls_handshake() failed: The server name sent was not recognized
12:09:01   #6 3.901 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**When did the issue occur?**
September 11 10:30 AM 

**If applicable, what package did you attempt to install, and from which repo?**
mssql-tools/
Repo: https://packages.microsoft.com/debian/9/prod/pool/main/m/mssql-tools/
Version: 17.5.1.2.1

**Steps to Reproduce**
Just browse in the repo 
https://packages.microsoft.com/debian/9/prod/pool/main/m/mssql-tools/

**Actual Result**
The webpage at https://pmc-geofence.trafficmanager.net/debian/9/prod/pool/main/m/mssql-tools/mssql-tools_17.6.1.1-1_amd64.deb?geofence=true might be temporarily down or it may have moved permanently to a new web address.
**Expected Result**

download the package 

**Screenshots**

**Additional context**

**Comment by daviddavis** [comment]
Going to close this in favor of https://github.com/microsoft/linux-package-repositories/issues/170.
