### ISSUE TITLE
Licensing Regarding Package / Repository Mirroring

### ISSUE THREAD

**Issue by gordan-bobic** [microsoft/linux-package-repositories#172]
What is the licensing on these packaging in terms of redistributing them via, for example, mirroring?
Or shipping them as part of other things, e.g. docker images?
Specifically in the context of microsoft-azurevpnclient Ubuntu .deb. packages.

Is it acceptable to make such things downloadable as part of other things?
My concern with relying on the packages.microsoft.com repositories is that Linux packages have been removed from there in the past, e.g. Teams, which breaks automated build pipelines unless local private mirrors/archives are used.

**Comment by acheng-01** [comment]
@gordan-bobic thanks for opening this issue. Unfortunately, there is a not a simple answer to this question, as each package has its own license and thus its own rules for distribution/usage. Furthermore, we (the engineers supporting packages.microsoft.com) are not in a position to provide legal advice on this or other matters. Our recommendation is to familiarize yourself with the licenses of any content you intend to mirror. You may also reach out to the development community driving specific projects if you have questions regarding those products.

Closing this issue as non-actionable.
