### ISSUE TITLE
Hash sum mismatch when attempting to install azcmagent on Ubuntu 22.04

### ISSUE THREAD

**Issue by Jack-Hazelden-Blackdot** [microsoft/linux-package-repositories#173]
**Describe the issue**
When attempting to install the Azure Arc agent onto a Ubuntu 22.04 machine the downloaded install script `install_linux_azcmagent.sh` fails partway through as the `azcmagent_1.46.02809.1707_amd64.deb` package fails the hash sum check.

**When did the issue occur?**
16SEP24 - previously worked without an issue 06SEP24 which was the last time we checked.

**If applicable, what package did you attempt to install, and from which repo?**
Package is - `https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/a/azcmagent/azcmagent_1.46.02809.1707_amd64.deb`

This was triggered via the script downloaded from `https://aka.ms/azcmagent`

**Steps to Reproduce**
1. Setup a clean Ubuntu 22.04 machine - one used was an AWS machine with the AMI `ami-00b2b33fc1d323a54`
2. Run the following:

```
# Download the installation package
wget https://aka.ms/azcmagent -O ~/install_linux_azcmagent.sh

# Install the hybrid agent
sudo bash ~/install_linux_azcmagent.sh
```

**Actual Result**
Install script errors as the `azcmagent_1.46.02809.1707_amd64.deb` package it downloaded fails the hash sum check.

> E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/a/azcmagent/azcmagent_1.46.02809.1707_amd64.deb  Hash Sum mismatch
>    Hashes of expected file:
>     - SHA256:7c96c04a956b16b866c56c2c55abdd5565342b0392019cd5e2edb65171287d95
>     - Filesize:67295686 [weak]
>    Hashes of received file:
>     - SHA256:88f2366f330550332ab2fc83042113dd51482f6a427b7bfb1818b547d4ab19a9
>     - Filesize:67295686 [weak]
>    Last modification reported: Tue, 10 Sep 2024 21:48:24 +0000

**Expected Result**

Hashes should match and the install script should execute without issue. The `azcmagent` command can be called to verify the Azure Arc agent has installed successfully.

**Comment by daviddavis** [comment]
@Jack-Hazelden-Blackdot can you tell me what country you are located in? Also, can you give me the output from curl:

```
curl --head https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/a/azcmagent/azcmagent_1.46.02809.1707_amd64.deb
```

And what sha256 you see when you download the package:

```
wget https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/a/azcmagent/azcmagent_1.46.02809.1707_amd64.deb
sha256sum azcmagent_1.46.02809.1707_amd64.deb
```

**Comment by Jack-Hazelden-Blackdot** [comment]
@daviddavis 

The country is the UK - deploying from AWS `eu-west-2` region.

When downloading via the `wget` command above the sha256 is `7c96c04a956b16b866c56c2c55abdd5565342b0392019cd5e2edb65171287d95` which I believe is the expected one.

**Comment by daviddavis** [comment]
That is the correct hash digest. We had some CDN issues this morning in the UK region. I've manually purged the file from our cache. Can you see if you are still experiencing the problem?

**Comment by Jack-Hazelden-Blackdot** [comment]
@daviddavis The problem seems to be resolved - appreciate your help!
