### ISSUE TITLE
Repos file size mismatch

### ISSUE THREAD

**Issue by fadnincx** [microsoft/linux-package-repositories#174]
**Describe the issue**
Looking at the metadata https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/InRelease , then
https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-amd64/Packages.gz: size check mismatch 313493 != 313128 

The same goes with metadata from https://packages.microsoft.com/repos/edge/dists/stable/InRelease and then 
https://packages.microsoft.com/repos/edge/dists/stable/main/binary-amd64/Packages.gz: size check mismatch 11350 != 11210

And https://packages.microsoft.com/repos/vscode/dists/stable/InRelease and
https://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.gz: size check mismatch 26915 != 26670

**When did the issue occur?**
For at least since Sept 12th until creation of this issue

**If applicable, what package did you attempt to install, and from which repo?**

**Steps to Reproduce**

Check file size documented in `InRelease`, and compare to actual file size

**Actual Result**
Size don't match

**Expected Result**
Size Match

**Screenshots**

**Additional context**

**Comment by daviddavis** [comment]
@fadnincx it's possible that these files will be out of sync. We are considering lowering the TTL so the window will be smaller but really you should be using [the by-hash files](https://wiki.ubuntu.com/AptByHash) which we provide (e.g. https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-amd64/by-hash/). I am curious why are you pulling the Packages.gz instead of the by-hash files?

**Comment by fadnincx** [comment]
For one, I'm trying to mirror the repos with [Aptly](https://github.com/aptly-dev/aptly) (the same software apparently used to publish the repos (at least according to the description) so my influence on that files of a repo are used how is quite limited and second of all, it doesn't help, if one gets a 404 when trying to access the resources. In my opinion, older versions should stay online at least for some time. But the by-hash file contains only the most recent version.

Digging a bit deeper, it seems that the 'InRelease' file containing the hashes, file size and filenames, already has a caching issue.

When using curl on `https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/InRelease` with explicitly asking for no cache:
```
*   Trying 13.107.246.60:443...
* Connected to packages.microsoft.com (13.107.246.60) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=WA; L=Redmond; O=Microsoft Corporation; CN=packages.microsoft.com
*  start date: Sep 11 14:10:52 2024 GMT
*  expire date: Sep  6 14:10:52 2025 GMT
*  subjectAltName: host "packages.microsoft.com" matched cert's "packages.microsoft.com"
*  issuer: C=US; O=Microsoft Corporation; CN=Microsoft Azure RSA TLS Issuing CA 04
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55b42395eb20)
> GET /ubuntu/20.04/prod/dists/focal/InRelease?1726516400 HTTP/2
> Host: packages.microsoft.com
> user-agent: curl/7.74.0
> accept: */*
> cache-control: no-cache
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< date: Mon, 16 Sep 2024 19:53:20 GMT
< content-type: application/octet-stream
< content-length: 3632
< last-modified: Wed, 11 Sep 2024 08:40:03 GMT
< etag: "0x8DCD23D54D4A1FD"
< x-ms-request-id: 6da57028-f01e-0000-5727-04a06d000000
< x-ms-version: 2024-08-04
< x-ms-version-id: 2024-09-11T08:40:03.7827069Z
< x-ms-is-current-version: true
< x-ms-creation-time: Wed, 11 Sep 2024 08:40:03 GMT
< x-ms-blob-content-md5: ny6TOkS08eaJ/8QsqHam+w==
< x-ms-lease-status: unlocked
< x-ms-lease-state: available
< x-ms-blob-type: BlockBlob
< content-disposition: attachment;filename=InRelease
< x-ms-server-encrypted: true
< strict-transport-security: max-age=31536000; includeSubDomains
< x-content-type-options: nosniff
< x-azure-ref: 20240916T195320Z-1794b988df8kqgr7wy89a4assg00000006k0000000008fn1
< x-cache: TCP_HIT
< cache-control: public, max-age=300
< x-fd-int-roxy-purgeid: 66949960
< accept-ranges: bytes
< 
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Origin: microsoft-ubuntu-focal-prod focal
Label: microsoft-ubuntu-focal-prod focal
Suite: focal
Codename: focal
Date: Wed, 11 Sep 2024 08:34:49 +0000.
Architectures: amd64 arm64 armhf all
Components: main
Description: Generated by aptly
Acquire-By-Hash: yes
....
```

while opening the same in firefox gives:
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Origin: microsoft-ubuntu-focal-prod focal
Label: microsoft-ubuntu-focal-prod focal
Suite: focal
Codename: focal
Date: Mon, 16 Sep 2024 16:53:36 +0000
Architectures: amd64 arm64 armhf all
Components: main
Description: Generated by aptly
Acquire-By-Hash: yes
...
```

Digging into the http header, the difference seems to be with `Accept-Encoding: gzip` or `Accept-Encoding: br`. So definitely something on the cache-level is wrong

**Comment by daviddavis** [comment]
We did generate some of the repos at one time using aptly but we no longer use it. I assume that aptly is not using by-hash to mirror repos?

> In my opinion, older versions should stay online at least for some time. But the by-hash file contains only the most recent version.

They should remain available from 3 days for up to 1 year. If you are using the html directory listing, then that's only showing the files in the latest version of the repo. It doesn't show the cached files including the cached by-hash files but they should still be available to download even though they aren't listed.

I'm also seeing issues with different versions of the InRelease file being returned so I've asked the CDN team to investigate.

**Comment by smnsez21** [comment]
This exact scenario is impacting me. While it is "only" one repo, when relying on the replicated copy (we user https://github.com/apt-mirror/apt-mirror/blob/master/apt-mirror), it prevents our entire automation (puppet) from running. 
Can you please regenerate the Packages.gz with the "correct" values (well, at least to let 'apt update' run).

**Comment by fadnincx** [comment]
> We did generate some of the repos at one time using aptly but we no longer use it. I assume that aptly is not using by-hash to mirror repos?

I can neither confirm nor deny that aptly uses by-hash or not, because it might fall back to files if the hash files are not available.

> > In my opinion, older versions should stay online at least for some time. But the by-hash file contains only the most recent version.
> 
> They should remain available from 3 days for up to 1 year. If you are using the html directory listing, then that's only showing the files in the latest version of the repo. It doesn't show the cached files including the cached by-hash files but they should still be available to download even though they aren't listed.

I have not yet found any files via hash that are not latest and available. So no, it does not seem that they are just excluded from the html file listing, but that they are not available at all.

Picking any hash from the InRelease version 9/11/24 currently delivered to curl give me a 404 error, such as for example (taking the first 3 hashes)
 * https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-amd64/by-hash/SHA256/adf7a01031efa32e2b8ecef4608f8c17e496df978f2bcb983a9baec3d90599e0
 * https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-amd64/by-hash/SHA256/c69501ca49ce1174fb08347ce2e1e22a1e5cb0347da17fc039c60f6680a1962a
 * https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-amd64/by-hash/SHA256/b698a175c9b594ff561ae2e5cfc2a3a51a79f3f1afe9a1adc0aacb5f3f74867d

**Comment by daviddavis** [comment]
The by-hash files are stored in cache for at least three days after they are removed from the repo. These were removed on September 12 so they probably became unavailable sometime after September 15 but before today. We can increase that but right now I think the bigger problem is figuring out why old versions of InRelease are still being served.

**Comment by adityamaru** [comment]
Just chiming in that we're seeing this too on some of our machines running in eu-central-1. Is there a workaround that we can apply while this is being resolved?

```
Reading package lists...
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/main/binary-arm64/Packages.gz  File has unexpected size (43334 != 43043). Mirror sync in progress? [IP: 13.107.253.45 443]
   Hashes of expected file:
    - Filesize:43043 [weak]
    - SHA512:88b58c2d6a0cebf09[63]
   Release file created at: Thu, 12 Sep 2024 18:17:22 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by daviddavis** [comment]
We think that during our infrastructure deployment last week, apt metadata files (InRelease, Packages.gz, etc) became stored in our CDN cache with longer than expected TTLs. I've gone through and purged all apt metadata files from our cache, which should fix the problem. Would be interested to know if anyone is still experiencing issues.

**Comment by smnsez21** [comment]
Re-pulled repo today - all is well now.

**Comment by smnsez21** [comment]
Now getting the same problem with the microsoft-edge-stable repo..

**Comment by smnsez21** [comment]
Re-pulled the edge repo again - all is well now.  Thanks.

**Comment by fadnincx** [comment]
All good for me. Curious to see if the cache TTL issue is solved permanently or just for now, because old versions have been manually purged.
