### ISSUE TITLE
`dotnet-sdk-6.0` not available on Ubuntu 24.04

### ISSUE THREAD

**Issue by justinmchase** [microsoft/linux-package-repositories#177]
**Describe the issue**
I am unable to install dotnet 6 runtime and sdk on Ubuntu `24.04`

**When did the issue occur?**
It seems like it has always been the case for Ubuntu `24.04`

**If applicable, what package did you attempt to install, and from which repo?**

https://packages.microsoft.com/ubuntu/24.04/prod

* `dotnet-sdk-6.0`
* `dotnet-runtime-6.0`
* `aspnetcore-runtime-6.0`

**Steps to Reproduce**

```sh
curl -sSL  https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
sudo apt-add-repository https://packages.microsoft.com/ubuntu/24.04/prod
sudo apt update
sudo apt install -y \
  dotnet-sdk-6.0 \
  dotnet-runtime-6.0 \
  aspnetcore-runtime-6.0
```

**Actual Result**

> E: Package 'dotnet-sdk-6.0' has no installation candidate

**Expected Result**

`8.0` is installing fine, I would expect `6.0` to also install fine but for some reason it is not.

**Screenshots**
![image](https://github.com/user-attachments/assets/b5322a8a-9edc-4d58-99ca-9e0b51831728)

**Additional context**
| Key | Value |
| --- | --- |
| Arch | `amd64` |
| Dist | `noble` |
| Version | `24.04` |

**Comment by acheng-01** [comment]
@justinmchase thank you for opening this issue. For your reference, please see this issue from the dotnet team's repository: https://github.com/dotnet/sdk/issues/40025

It seems like they are not publishing dotnet-sdk to ubuntu 24.04. Please reach out to them on any additional follow-up for this. I'm closing this issue.
