### ISSUE TITLE
Sources of the packages

### ISSUE THREAD

**Issue by hecko** [microsoft/linux-package-repositories#26]
I have spent significant time debugging one of the issues we are having with unixODBC distribution from MS repos installed from 

https://packages.microsoft.com/rhel/7/prod/unixODBC-utf16-2.3.1-1.x86_64.rpm

I can definitely see some patches being applied on top of the official unixODBC distribution from http://www.unixodbc.org/ as the functionality is so slightly different (configuration-wise), but Im unable to find the sources to these patches.

Im specifically interested in seeing the code from which RPMs are build from, but this seems to be impossible to find from my perspective. Can anyone please provide a link to the build sources - similar to https://packages.debian.org/source/buster/unixodbc for Debian?

**Comment by hecko** [comment]
I would really appreciate some response to this in any capacity please.

**Comment by Klaas-** [comment]
I think that's a modified rhel package ("Recompile unixODBC with UTF16 character conversion enabled by default" if you trust the changelog), according to the rpm its gpl/lgpl licensed, so you should be able to get the sources from MS, maybe try writing the to team that  packages it mssql-odbc@microsoft.com :)

**Comment by hecko** [comment]
Thanks @Klaas- - can you link the changelog please? 

Thank you very much for the response!

**Comment by daviddavis** [comment]
If you run `rpm -q --changelog unixODBC-utf16-2.3.1-1.x86_64.rpm` you can see the changelog.

**Comment by hecko** [comment]
mssql-odbc@microsoft.com returns as non-existent mailbox and dpgswdist@microsoft.com is limited to receive emails from within microsoft.com domain - so disappointing.

**Comment by mbearup** [comment]
> [mssql-odbc@microsoft.com](mailto:mssql-odbc@microsoft.com) returns as non-existent mailbox and [dpgswdist@microsoft.com](mailto:dpgswdist@microsoft.com) is limited to receive emails from within microsoft.com domain - so disappointing.

Apologies for the obstacles here. We (the PMC admins) are working with the package maintainers to fulfill your request. For future reference, you can reach out to [opensource@microsoft.com](mailto:opensource@microsoft.com) to request source code for packages such as this, as documented [here](https://packages.microsoft.com/docs/source.txt).

**Comment by David-Engel** [comment]
Hi @hecko 

Sorry for the delay. It took a good bit of digging into history and verifying, but we confirmed the package was built from the unixodbc 2.3.1 source at http://www.unixodbc.org/unixODBC-2.3.1.tar.gz with specific build options.

For convenience, here is an attached zip file of the source along with build scripts and instructions required to reproduce the package byte-for-byte.

[unixODBC-utf16 sources.zip](https://github.com/microsoft/linux-package-repositories/files/10855658/unixODBC-utf16.sources.zip)

Regards,
David

**Comment by Klaas-** [comment]
@David-Engel / @daviddavis  maybe just publish source rpms of the packages you publish here (at least for the ones that are meant to be open source), that would make questions like this really easy to answer :)

**Comment by daviddavis** [comment]
@Klaas- yes, we're recommending that package maintainers upload package sources. And we're adding features to better enable that.

**Comment by daviddavis** [comment]
Seems like the sources have been posted. Closing as completed.
