### ISSUE TITLE
[RHEL9] packages-microsoft-prod.rpm uses wrong baseurl

### ISSUE THREAD

**Issue by Klaas-** [microsoft/linux-package-repositories#33]
**Describe the issue**
http://packages.microsoft.com/rhel/9/prod/Packages/p/packages-microsoft-prod.rpm 
uses
`baseurl=https://packages.microsoft.com/rhel/9.0/prod`
it should be using
`baseurl=https://packages.microsoft.com/rhel/9/prod`

**If appplicable, what package did you attempt to install, and from which repo?**
http://packages.microsoft.com/rhel/9/prod/Packages/p/packages-microsoft-prod.rpm 

**Steps to Reproduce**
dnf install http://packages.microsoft.com/rhel/9/prod/Packages/p/packages-microsoft-prod.rpm 
grep baseurl /etc/yum.repos.d/microsoft-prod.repo

**Actual Result**
`baseurl=https://packages.microsoft.com/rhel/9.0/prod`

**Expected Result**
`baseurl=https://packages.microsoft.com/rhel/9/prod`

**Comment by sdherr** [comment]
Hi Klaas, thanks for the report but this actually irrelevant as they are both aliases to the same content. In the future hopefully we won't duplicate the repos and cause such confusion.
