### ISSUE TITLE
[RHEL 8][azure-cli + azure-cli-iot] Minimium Requirement not satisfied because of hardcoded python 3.6

### ISSUE THREAD

**Issue by MichaelKx** [microsoft/linux-package-repositories#35]
Hello, 
there is a conflict between the azure-cli version and the documentation.
azure-iot-cli-extension states that the minium required azure-cli version is v2.32.0
azure-cli packages for RHEL hardcode the python version 3.6 until azure-cli v2.39.
This hardcoded version prevents the latest azure-iot-cli-extension to be installed, because a dependency needs at least python 3.7 (tomli 2.0)
If possible, please change the hardcoded python version or correct the documentation accordingly.
REFERENCES:
- https://github.com/Azure/azure-iot-cli-extension#installation
- https://github.com/Azure/azure-iot-cli-extension/issues/624

Thank you!

**Comment by mbearup** [comment]
@MichaelKx ,
Thanks for bringing this to our attention. I've relayed your concern to the azure-cli team, who maintains this package.
This repo is primarily used for tracking the _package delivery infrastructure_. A better place for this issue would be [the azure-cli github page](https://github.com/Azure/azure-cli/issues). I'll be closing this issue, but feel free to create an issue directly with azure-cli if you want further updates on this issue.
