### ISSUE TITLE
omi and scx packages missing digest information for RHEL

### ISSUE THREAD

**Issue by sodds-eq** [microsoft/linux-package-repositories#40]
Packages: 
* omi
* scx
These packages does not contain digest information, which means they will fail to install on a system that is running in FIPS mode.
The packages are available in both RHEL and packages.microsoft.com, and the latter is needed for getting mdatp packages.

So in my mind the packages.microsoft.com repository should contain all necessary digest information to avoid having to use --nodigest --nofiledigest for updating from it.

**Comment by mbearup** [comment]
I have forwarded your request to the team that drives omi/scx packages.

**Comment by jasonzio** [comment]
Please [open an issue directly with the OMI team](https://github.com/microsoft/omi/issues). The PMC service is responsible for delivering packages, but we have no control over what's in those packages.
