### ISSUE TITLE
Ms Teams release vanished from archive, download web page returns 404s

### ISSUE THREAD

**Issue by ABCMoNa** [microsoft/linux-package-repositories#42]
Attempting to download
https://www.microsoft.com/en-us/microsoft-teams/download-app#desktopAppDownloadregion
using the buttons there currently leading to
https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.5.00.23861_amd64.deb
and
https://packages.microsoft.com/yumrepos/ms-teams/teams-1.5.00.23861-1.x86_64.rpm
(via redirects)
results in 404 errors.

None of the methods for downloading Ms Teams for Linux described at
https://learn.microsoft.com/en-us/microsoftteams/get-clients?tabs=Linux
currently seem to be available.

Was this release pulled? If so, is there a public statement as to why? Is there a slightly older version which is still available and safe to use?

What is the currently recommended approach for installing Ms Teams client on Linux?

Thanks.

**Comment by daviddavis** [comment]
See https://github.com/microsoft/linux-package-repositories/issues/41#issuecomment-1444314811.
