### ISSUE TITLE
Teams not found

### ISSUE THREAD

**Issue by willidert** [microsoft/linux-package-repositories#43]
**Describe the issue**
I wnat download microsoft teams but the [link](https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.5.00.23861_amd64.deb) returns a 404.

**When did the issue occur?**
When i try download teams, i have the same status code with curl and wget.

**If applicable, what package did you attempt to install, and from which repo?**

i'm trying download microsoft teams from official page

**Steps to Reproduce**
1. go to [link](https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.5.00.23861_amd64.deb)

**Actual Result**

returns a 404

**Expected Result**

start download

**Screenshots**
![image](https://user-images.githubusercontent.com/50498376/221905329-e4f61f92-c234-44b3-be3c-b25a5d35c049.png)

**Additional context**
i'm on ubuntu 22.04

**Comment by daviddavis** [comment]
See https://github.com/microsoft/linux-package-repositories/issues/41#issuecomment-1444314811
