### ISSUE TITLE
Consistently slow download speeds on packages.microsoft.com

### ISSUE THREAD

**Issue by yellowjacketcoder** [microsoft/linux-package-repositories#50]
**Describe the issue**
Getting consistently slow speeds on packages.microsoft.com for apt packages atleast(code in my case). Somewhere around 50KiB/s even when I am on a 300Mbps connection and getting 22-30MiB/s on other repositories.

**When did the issue occur?**
Has been a constant issue since atleast the past 6 months for me

**If applicable, what package did you attempt to install, and from which repo?**
code,  from https://packages.microsoft.com/repos/code

**Steps to Reproduce**
setup code repo, install code, check download speed

**Actual Result**
~50KiB/s

**Expected Result**
1MiB/s atleast?

**Screenshots**
![Screenshot of a linux terminal in which a curl command is running that is downloading azure-cli from packages.microsoft.com. The speed is shown to be 49,478 bytes per second](https://i.ibb.co/3YfyvXd/Screenshot-from-2023-04-01-13-28-01.png)
[Source](https://i.ibb.co/3YfyvXd/Screenshot-from-2023-04-01-13-28-01.png)

**Additional context**
I am located in en-IN/India/Asia Pacific region

**Comment by o-r-e** [comment]
May be same as #58 .
Hi, @daviddavis !
I can see slow speeds same as @yellowjacketcoder (50-80 kB/s) . My output of `dig packages.microsoft.com` is:
```$ dig packages.microsoft.com

; <<>> DiG 9.18.12-0ubuntu0.22.04.1-Ubuntu <<>> packages.microsoft.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20333
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;packages.microsoft.com.		IN	A

;; ANSWER SECTION:
packages.microsoft.com.	1678	IN	CNAME	apt-geofence-parent.trafficmanager.net.
apt-geofence-parent.trafficmanager.net.	300 IN CNAME csd-apt-weu-d-1.westeurope.cloudapp.azure.com.
csd-apt-weu-d-1.westeurope.cloudapp.azure.com. 4 IN A 13.80.99.124

;; Query time: 76 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Sat Jun 03 10:20:22 +06 2023
;; MSG SIZE  rcvd: 175```

**Comment by o-r-e** [comment]
May be same as #58.
Hi, @daviddavis !
I can see same slow speeds as @yellowjacketcoder - 50-80 KB/s. My output of `dig packages.microsoft.com` is:

<pre><code>$ dig packages.microsoft.com

; <<>> DiG 9.18.12-0ubuntu0.22.04.1-Ubuntu <<>> packages.microsoft.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20333
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;packages.microsoft.com.		IN	A

;; ANSWER SECTION:
packages.microsoft.com.	1678	IN	CNAME	apt-geofence-parent.trafficmanager.net.
apt-geofence-parent.trafficmanager.net.	300 IN CNAME csd-apt-weu-d-1.westeurope.cloudapp.azure.com.
csd-apt-weu-d-1.westeurope.cloudapp.azure.com. 4 IN A 13.80.99.124

;; Query time: 76 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Sat Jun 03 10:20:22 +06 2023
;; MSG SIZE  rcvd: 175</code></pre>

But I have funny "workaround" - usually I just need right time of day :D . Slow speeds 50-80 KB/s are present at day time at UTC timezone, but at 4:20 UTC (10:20 +06) I can get:

<pre><code>$ wget https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_114.0.1823.37-1_amd64.deb?brand=M102_.%25
--2023-06-03 10:49:49--  https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_114.0.1823.37-1_amd64.deb?brand=M102_.%25
Resolving packages.microsoft.com (packages.microsoft.com)... 13.81.215.193
Connecting to packages.microsoft.com (packages.microsoft.com)|13.81.215.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 147255626 (140M) [application/octet-stream]
Saving to: ‘microsoft-edge-stable_114.0.1823.37-1_amd64.deb?brand=M102_.%’

microsoft-edge-stable_114.0.1823. 100%[============================================================>] 140,43M  17,0MB/s    in 9,2s    

2023-06-03 10:49:59 (15,2 MB/s) - ‘microsoft-edge-stable_114.0.1823.37-1_amd64.deb?brand=M102_.%’ saved [147255626/147255626]</code></pre>

**Comment by kbs1** [comment]
Whenever I update packages from packages.microsoft.com (my location is Slovakia), I get ~60kb/s download speed. It takes 20 minutes just to update VS Code. I am hitting exactly the same server as @o-r-e

**Comment by mbearup** [comment]
This week we're converting our edge delivery strategy to use Azure Front Door (AFD). This should result in improved performance for most users, as AFD has [192 points of presence](https://learn.microsoft.com/en-us/azure/frontdoor/edge-locations-by-region) (and growing) around the globe.
As of today, all packages.microsoft.com traffic in APAC is served through Front Door. Assuming no major obstacles, AFD should be serving all packages.microsoft.com traffic across the globe by end of next week.

**Comment by timbodv** [comment]
@mbearup As an observation since 2024-03-02 we've been inconsistently seeing access denied messages when attempting to update the package repository on SUSE (other Linux distributions seem to be unaffected).

~~~~
> zypper se mdatp azcmagent

Refreshing service 'SUSE_Linux_Enterprise_Server_x86_64'.
Permission to access 'https://packages.microsoft.com/sles/12/prod/media.1/media?proxy=<our proxy>&proxyport=<our proxy port>' denied.
Abort, retry, ignore? [a/r/i/...?
~~~~

In our repo file we have the following configured `baseurl="https://packages.microsoft.com/sles/12/prod/?proxy=<our proxy>&proxyport=<our proxy port>"` which we've been using for a few months without issue. Strangely the issue appeared resolved on Monday 2024-03-04 but has since returned today. Might this be related to the AFD change?

**Comment by daviddavis** [comment]
@timbodv I think I've found the problem. can you open a new issue?

**Comment by daviddavis** [comment]
@timbodv I believe your issue should be solved. Please let us know if you any other problems by filing a new issue.
