### ISSUE TITLE
Need IP range for this resource to allow through company firewalls

### ISSUE THREAD

**Issue by wstr-ncrum** [microsoft/linux-package-repositories#53]
**Describe the problem you are experiencing.**

We have an on-premises CICD tool and one of our containers needs to pull from packages.microsoft.com. It is blocked by our company firewall and they require that we provide a static list of IP addresses to allow through and not an FQDN

**Describe any possible solutions that you would like to see.**

Could you publish a page or add to the default landing page the public IP's to expect for this page or a CIDR range if it could rotate between a few?

**Additional context.**

**Comment by jasonzio** [comment]
Updates to our edge delivery infrastructure may result in new VMs with new IP addresses being added to service pools and old VMs dropping out. The IP addresses in use could come from any IP address block allocated to Microsoft Azure.

Microsoft publishes its allocated IP address blocks and updates them as they change. See https://www.microsoft.com/en-us/download/details.aspx?id=53602.
