### ISSUE TITLE
Debian: File has unexpected size (66877 != 66951)

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/linux-package-repositories#54]
@henrytill, from https://github.com/microsoft/vscode/issues/180947

> - VS Code Version: N/A
> - OS Version: Debian Testing
> 
> Steps to Reproduce:
> 
> 1. Ensure that you have the following in `/etc/apt/sources.list.d/vscode.list`:
> ```
> ### THIS FILE IS AUTOMATICALLY CONFIGURED ###
> # You may comment out this entry, but any other modifications may be lost.
> deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/code stable main
> ```
> 2. Run `sudo apt update`.  You should see something like the following:
> 
> ```
> Err:5 http://packages.microsoft.com/repos/code stable/main arm64 Packages
>   File has unexpected size (66877 != 66951). Mirror sync in progress? [IP: 13.93.152.112 80]
>   Hashes of expected file:
>    - Filesize:66951 [weak]
>    - SHA512:c7d69259f8667ecfa7a3c7ae8a727984091dae27d5aba1e9641c6d6ba0db69979d1c66bd1ab2a0f5c625b2f20e2d3eeb6b613b2278016215ba3e140b9efb1a04
>    - SHA256:b77837862bcdb1d00aee0943ea1b07789519af2da0841a87cb60f9adfba41dec
>   Release file created at: Wed, 26 Apr 2023 06:55:46 +0000
> ```

**Comment by daviddavis** [comment]
Can you tell me which mirror you're using? `dig packages.microsoft.com` should say something like csd-apt-eus-d-1.eastus.cloudapp.azure.com.

**Comment by daviddavis** [comment]
I guess this question is probably for @henrytill.

**Comment by daviddavis** [comment]
The file seems ok to me but it's possible I am hitting a different mirror.

```
$ curl -O https://packages.microsoft.com/repos/code/dists/stable/main/binary-arm64/Packages.gz

$ sha256sum Packages.gz
b77837862bcdb1d00aee0943ea1b07789519af2da0841a87cb60f9adfba41dec  Packages.gz

$ ls -l Packages.gz
-rw-rw-r-- 1 david david 66951 Apr 26 19:35 Packages.gz
```

**Comment by henrytill** [comment]
Started working as expected again.  Apologies for the traffic.

**Comment by henrytill** [comment]
> Can you tell me which mirror you're using? `dig packages.microsoft.com` should say something like csd-apt-eus-d-1.eastus.cloudapp.azure.com.

Current results of `dig packages.microsoft.com` (working as expected):
```
; <<>> DiG 9.18.12-1-Debian <<>> packages.microsoft.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45724
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;packages.microsoft.com.		IN	A

;; ANSWER SECTION:
packages.microsoft.com.	3532	IN	CNAME	apt-geofence-parent.trafficmanager.net.
apt-geofence-parent.trafficmanager.net.	232 IN CNAME csd-apt-wus-d-2.westus.cloudapp.azure.com.
csd-apt-wus-d-2.westus.cloudapp.azure.com. 3 IN	A 13.93.224.173

;; Query time: 15 msec
;; SERVER: 1.1.1.1#53(1.1.1.1) (UDP)
;; WHEN: Wed Apr 26 12:38:27 PDT 2023
;; MSG SIZE  rcvd: 171
```

**Comment by daviddavis** [comment]
Great, thanks for the update.
