### ISSUE TITLE
download speed is really too slow

### ISSUE THREAD

**Issue by jianjianxu** [microsoft/linux-package-repositories#58]
Everytime I updated edge and vscode on my ubuntu22.04, the speed is really so slow, less than `80K/s`.
Is there anyway I can speed up?
this is my info :
```
jj@RRp:~$ dig packages.microsoft.com

; <<>> DiG 9.18.12-0ubuntu0.22.04.1-Ubuntu <<>> packages.microsoft.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18409
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;packages.microsoft.com.		IN	A

;; ANSWER SECTION:
packages.microsoft.com.	1083	IN	CNAME	apt-geofence-parent.trafficmanager.net.
apt-geofence-parent.trafficmanager.net.	195 IN CNAME csd-apt-eas-d-2.eastasia.cloudapp.azure.com.
csd-apt-eas-d-2.eastasia.cloudapp.azure.com. 195 IN A 65.52.183.205

;; Query time: 4 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Sat May 13 17:31:49 CST 2023
;; MSG SIZE  rcvd: 173
```

**Comment by jasonzio** [comment]
We are aware that download throughput in parts of Asia, especially from within China, are slower than we'd like. Addressing this in a manner that complies with all relevant regulatory authorities is challenging, but we are committed to solving it. Thank you for your patience.

**Comment by kbs1** [comment]
@jasonzio this also happens in Central Europe (Slovakia), I don't remember a time when I had > 80kb/s download speed. It is like this for at least 6 months now. No VPN, multiple machines, windows or linux, the same result. I am using DNS servers provided by my local ISP (UPC Slovakia - https://www.upc.sk/) hitting `csd-apt-weu-d-1.westeurope.cloudapp.azure.com. 4 IN A 13.80.99.124`

**Comment by acheng-01** [comment]
Hello all, we are aware that slow download speeds have been an issue and are actively working to resolve it. We should have a fix coming soon to help.

In the meantime, I will be closing this issue as a dupe to #50. Please refer to that thread to voice any other concerns and follow updates from our end. Thank you for your patience!
