### ISSUE TITLE
Need Updated azure-client binary versions in RPM format - CentOS 8.5

### ISSUE THREAD

**Issue by james-ault-nnl** [microsoft/linux-package-repositories#61]
**Describe the issue**
An Azure VM is running CentOS 8.5 (CentOS release = CentOS Linux release 8.5.2111)
and it will not discover azure-client binaries newer than 2.38.0. 

Microsoft Rep asked me to create this issue: "
See this official release notes page, James: Manuals/ReleaseNotes/CentOS8.2111 - CentOS Wiki
 
It appears this version of CentOS went EoL on Dec. 31, 2021 and CentOS 8 Stream needs to be used instead. I'm not sure if this is related, but do note this EoL status.
 
It looks like https://packages.microsoft.com/yumrepos/azure-cli/Packages/a/ hold no versions of azure-cli above 2.38, so if possible, can you please create a new Github issue with this same request in the Linux Package Repositories github repository, so that the maintainers can properly address why the updated AZ CLI packages aren't made available? This is the best course of action at this time as it will allow you to open direct communication with the repo maintainers about the issue at hand here. let me know once that request is created as well.
 
Warm Regards,
 
Skylar Onstot"

The azure-cli rpm packages does not provide versions newer than 2.39.0.

**When did the issue occur?**
Anytime after 8/2/2022.
according to this page:
https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf

**If applicable, what package did you attempt to install, and from which repo?**

I attempted to install azure-cli from repo at  https://packages.microsoft.com/yumrepos/azure-cli

**Steps to Reproduce**

1) Install VM with CentOS 8.5
2) Install azure-cli repo
3) yum install azure-cli 
4) yum list --showduplicates azure-cli

**Actual Result**

azure-cli 2.39.0 was installed

**Expected Result**

azure-cli 2.49.0 would be installed. 

**Screenshots**

**Additional context**

This version of CentOS was selected because it appears on this webpage:
https://learn.microsoft.com/en-us/azure/virtual-machines/automatic-vm-guest-patching

If and when CentOS 8 Stream appears on the list of supported images for AzureOrchestratedPatching in this webpage, we will be glad to switch to that new OS version.

**Comment by daviddavis** [comment]
Hi @james-ault-nnl. We (the Linux packages team) own the packages.microsoft.com platform but we don't actually build any of the packages. This is up to the team who develops the software (in this case azure-cli). Please file your issue at https://github.com/Azure/azure-cli/issues.
