### ISSUE TITLE
Powershell missing from RHEL 9 Repository

### ISSUE THREAD

**Issue by mbrownewu** [microsoft/linux-package-repositories#62]
**Describe the problem you are experiencing.**
PowerShell is not in the Repository for RHEL 9 (https://packages.microsoft.com/rhel/9/) 

**Describe any possible solutions that you would like to see.**
Add PowerShell to the repository like it is for 7 and 8 so we can properly support/patch PowerShell on Linux systems.

**Comment by daviddavis** [comment]
Hi @mbrownewu, the Linux packaging team owns the package.microsoft.com platform but we don't build/maintain/publish packages to packages.microsoft.com. Please file an issue at https://github.com/PowerShell/PowerShell/issues.
