### ISSUE TITLE
[CENTOS7] Can't add repository and install mdatp

### ISSUE THREAD

**Issue by myanuararys** [microsoft/linux-package-repositories#64]
**Describe the issue**
Hi, 

We have try to add packages.microsoft.com as a repo, but it was always getting failed even though we have open the firewall to packages.microsoft.com port 443 / https. We need to install mdatp, but without adding this repo, it is not possible.

**When did the issue occur?**
Has been a constant issue since at least the one months for me

**If applicable, what package did you attempt to install, and from which repo?**

We try to install https://packages.microsoft.com/config/centos/7/prod.repo on our Centos 7. 

**Steps to Reproduce**

when we try command "`sudo yum-config-manager --add-repo=https://packages.microsoft.com/config/centos/7/prod.repo`" or "`curl -sSL https://packages.microsoft.com/config/centos/7/prod.repo | sudo tee /etc/yum.repos.d/microsoft-prod.repo`", 

**Actual Result**

it always failed due to timeout.

**Expected Result**
Success to add repo and install mdatp

**Screenshots**

Here are the error result :

![image](https://github.com/microsoft/linux-package-repositories/assets/49024926/815f31f2-1e42-4571-ae23-3a4da440381a)

**Additional context**
my server located in Malaysia/SouthEastAsia Region

Pls anybody can help,
Thanks

**Comment by jasonzio** [comment]
The https://packages.microsoft.com/config/centos/7/prod.repo file is available on all mirrors of packages.microsoft.com, and the mirrors in South East Asia are all on-line. The command you're running is correct, and I can't explain the timeout you saw. Are you certain you don't have a firewall or NSG setting which prevents you from accessing packages.microsoft.com?

**Comment by myanuararys** [comment]
Hi Jason,

Thanks for comment. I have found the root cause. It is MTU problem. When i set it to 1476, it works. It looks like packages.microsoft.com only accept MTU not greater than 1476.

**Comment by mbearup** [comment]
In the past ~45 days we renovated our delivery architecture to use Azure Front Door (a premier Content Delivery Network for enterprise scale). An MTU size of 1500 _should_ have been usable in our legacy infrastructure, but it's definitely supported by Azure Front door.
