### ISSUE TITLE
Report an issue

### ISSUE THREAD

**Issue by Wellrique** [microsoft/linux-package-repositories#69]
sudo apt update
[sudo] senha para wellington: 
E: Conflicting values set for option Signed-By regarding source https://packages.microsoft.com/repos/edge/ stable: /usr/share/keyrings/microsoft.gpg != 
E: Conflicting values set for option Signed-By regarding source https://packages.microsoft.com/repos/edge/ stable: /usr/share/keyrings/microsoft.gpg != 
E: A lista de fontes não pode ser lida.

**Comment by mbearup** [comment]
@Wellrique this issue typically occurs when multiple sources are defined with different signature verification definitions. Could you check the files under /etc/apt/sources.list.d to see if multiple entries exist for `https://packages.microsoft.com/repos/edge/`?

```
$ cat /etc/apt/sources.list.d/*.list
```
See also:
https://askubuntu.com/questions/1156409/conflicting-values-set-for-option-signed-by-regarding-source

**Comment by Wellrique** [comment]
Obrigado

Em seg., 24 de jul. de 2023 16:47, Matt Bearup ***@***.***>
escreveu:
