### ISSUE TITLE
Error: GPG Verification FAILED

### ISSUE THREAD

**Issue by rafadesign** [microsoft/linux-package-repositories#70]
Hi, I'm trying to update Microsoft Edge on Fedora 38 but I get an error message related to GPG verification

Current version:  114.0.1823.82 
Version I'm trying to update:  115.0.1901.183-1
System: Fedora 38

![image](https://github.com/microsoft/linux-package-repositories/assets/46974593/2940a3e8-e401-4cfd-bd71-42ddd6bf59c6)

**Comment by mbearup** [comment]
Thanks @rafadesign for reporting this issue. It looks like something went wrong with the package signing process before this package was published. I've reached out to the Edge team to get this package replaced with a correctly signed package.

**Comment by rafadesign** [comment]
> Thanks @rafadesign for reporting this issue. It looks like something went wrong with the package signing process before this package was published. I've reached out to the Edge team to get this package replaced with a correctly signed package.

Ok, Thankyou very much!

**Comment by rafadesign** [comment]
> The package with the invalid signature has been removed, and the team is working to publish a new version of the 115 package. Since yum/dnf refused to install the package (due to signature issues), there should be no one currently in a "broken" state. The 114 package will continue to function as expected until an updated package is released.

Ok, you are able to use version 114 without any problems, Thanks!
