### ISSUE TITLE
Request new release 1.6.22 for moby-containerd in https://debian.pkgs.org/11/microsoft-prod-amd64

### ISSUE THREAD

**Issue by frcai** [microsoft/linux-package-repositories#72]
**Describe the problem you are experiencing.**

Latest version for moby-containerd is 1.6.19. Can you help release new version 1.6.22 for moby-container? 1.6.22 addressed one potential vulnerability [issue ](https://github.com/advisories/GHSA-vvpx-j8f3-3w6h/) by https://github.com/containerd/containerd/pull/8642. Thanks a lot!

https://debian.pkgs.org/11/microsoft-prod-amd64/moby-containerd_1.6.19+azure-debian11u1_amd64.deb.html

**Describe any possible solutions that you would like to see.**

**Additional context.**

**Comment by mbearup** [comment]
Thanks for bringing this to our attention. An updated package should be published within the next 24 hours.
