### ISSUE TITLE
Unable to sync the packages.microsoft.com/rhel/8/prod/ repo because of microsoft-identity-diagnostics package

### ISSUE THREAD

**Issue by Joce99** [microsoft/linux-package-repositories#73]
Hi, 
I am using Suse Manager to sync the https://packages.microsoft.com/rhel/8/prod repository.
Since 2023-07-22, I am unable to sync the repo if I do not exclude the following package:
https://packages.microsoft.com/rhel/8/prod/Packages/m/microsoft-identity-diagnostics-1.0.0.x86_64.rpm

I have opened a case at Suse and they told me that I was not the first customer to complain about this.
They told me that this is caused but the fact that the "microsoft-identity-diagnostics-1.0.0.x86_64.rpm" does not have a **RELEASE** tag and this is violating rpm standards.

Fortunately, I do not need this package at the moment so I have applied a filter to exclude this package.
Suse is also probably going to patch their product to handle this kind of issues but I think that this package should be fixed anyway on your side.

More details : 

> wget https://packages.microsoft.com/rhel/8/prod/Packages/m/microsoft-identity-diagnostics-1.0.0.x86_64.rpm
> rpm -qi ./microsoft-identity-diagnostics-1.0.0.x86_64.rpm
> Name        : microsoft-identity-diagnostics
> Epoch       : 0
> Version     : 1.0.0
> **Release     :**
> Architecture: x86_64
> Install Date: (not installed)
> Group       : (none)
> Size        : 4101685
> License     :
> Signature   : RSA/SHA256, Fri Jul 21 12:52:42 2023, Key ID eb3e94adbe1229cf
> Source RPM  : microsoft-identity-diagnostics-1.0.0--src.rpm
> Build Date  : Thu Jul 20 18:32:18 2023
> Build Host  : fv-az125-367
> Relocations : (not relocatable)
> Packager    : root
> Vendor      :
> URL         :
> Summary     : microsoft-identity-diagnostics
> Description :
> 
> Distribution:

Note: I am not an expert with the rpm spec., I am simply relaying the information.  
Thanks
Jocelyn

**Comment by mbearup** [comment]
Thanks for bringing this to our attention. We've brought this issue up to the package creator/publisher and requested an updated package with the Release field populated.

**Comment by mbearup** [comment]
A new 1.0.1-1 package has been published (with the Release field populated) and the old 1.0.0 package has been removed. Let us know if you see further issues.
