### ISSUE TITLE
Problems installing libmsquic for dotnet 8 docker image

### ISSUE THREAD

**Issue by WhatzGames** [microsoft/linux-package-repositories#74]
**Describe the issue**
Trying to build a docker image based on aspnet:8-preivew failed when following steps to install libmsquic.

**When did the issue occur?**

I tried to install libmsquic from the [debian 12 repo](https://packages.microsoft.com/config/debian/12/)
according to the [docs](https://learn.microsoft.com/de-de/linux/packages#command-examples-for-using-the-linux-repository-service)

**Steps to Reproduce**

Have the following docker file
```dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:8.0-preview AS base
RUN apt-get update && apt-get install curl -y --no-install-recommends
RUN curl -sSL https://packages.microsoft.com/config/debian/12/prod.list | tee /etc/apt/sources.list.d/microsoft-prod.list
RUN curl -sSL https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc
RUN dpkg -i packages-microsoft-prod.deb
RUN rm packages-microsoft-prod.deb
RUN apt-get update && apt-get install libmsquic -y --no-install-recommends
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0-preview AS build
WORKDIR /src
COPY ["API/API.csproj", "API/"]
RUN dotnet restore "API/API.csproj"
COPY . .
WORKDIR "/src/API"
RUN dotnet build "API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "API.dll"]
```

And built the image

**Actual Result**
![grafik](https://github.com/microsoft/linux-package-repositories/assets/9288008/8b35fbe5-d3c2-4c88-b385-cd587511683e)

**Expected Result**
some sort of success status

**Additional context**

**Comment by daviddavis** [comment]
It looks like there's a step missing in the docs to download packages-microsoft-prod.deb. I've opened a PR to fix this:

https://github.com/daviddavis/linux/pull/1

That said though, I don't see any libmsquic package in the debian 12 repo: 

https://packages.microsoft.com/debian/12/prod/pool/main/

It does appear in the debian 11 repo:

https://packages.microsoft.com/debian/11/prod/pool/main/libm/libmsquic/

I'm guessing the msquic team hasn't built it yet for debian 12. I recommend filing an issue for them at https://github.com/microsoft/msquic/issues.
