### ISSUE TITLE
Debian 10 aziot-edge package seems to be corrupted

### ISSUE THREAD

**Issue by daveinci** [microsoft/linux-package-repositories#80]
**Describe the issue**

Installing aziot-edge on Raspberry Pi OS Buster via apt (Bullseye is unsupported still?) fails. The size of the package compared to the same in Debian 11 and github releases is smaller than expected. 

**When did the issue occur?**

8/31 1600-1700 US Central Time

**If applicable, what package did you attempt to install, and from which repo?**
https://packages.microsoft.com/debian/10/prod buster/main armhf aziot-edge armhf 1.2.9-1 

**Steps to Reproduce**

On Raspberry Pi OS Buster
curl https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb > ./packages-microsoft-prod.deb
sudo apt install ./packages-microsoft-prod.deb
sudo apt install aziot-edge defender-iot-micro-agent-edge

**Actual Result**
$ sudo apt install aziot-edge
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  aziot-edge
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 426 kB of archives.
After this operation, 20.1 MB of additional disk space will be used.
Get:1 https://packages.microsoft.com/debian/10/prod buster/main armhf aziot-edge armhf 1.2.9-1 [426 kB]
Fetched 426 kB in 1s (332 kB/s)
E: Invalid archive member header
E: Prior errors apply to /var/cache/apt/archives/aziot-edge_1.2.9-1_armhf.deb
debconf: apt-extracttemplates failed: No such file or directory
(Reading database ... 43674 files and directories currently installed.)
Preparing to unpack .../aziot-edge_1.2.9-1_armhf.deb ...
Unpacking aziot-edge (1.2.9-1) ...
dpkg-deb (subprocess): cannot copy archive member from '/var/cache/apt/archives/aziot-edge_1.2.9-1_armhf.deb' to decompressor pipe: unexpected end of file or stream
dpkg-deb (subprocess): decompressing archive member: lzma error: unexpected end of input
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive /var/cache/apt/archives/aziot-edge_1.2.9-1_armhf.deb (--unpack):
 cannot copy extracted data for './usr/bin/iotedge' to '/usr/bin/iotedge.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 /var/cache/apt/archives/aziot-edge_1.2.9-1_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Expected Result**
Successful install, no errors

**Screenshots**

**Additional context**

Following instructions here: 
https://learn.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-symmetric?view=iotedge-1.4&tabs=azure-portal%2Cdebian

Using Debian 10 (Buster) instead of 11 due to lack of support for Raspberry Pi OS Bullseye
https://learn.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-1.4

https://packages.microsoft.com/debian/11/prod/pool/main/a/aziot-edge/aziot-edge_1.2.9-1_armhf.deb = 4,863,144 bytes (4.63MB)
https://github.com/Azure/azure-iotedge/releases/download/1.2.9/aziot-edge_1.2.9-1_debian10_armhf.deb = 4.63 MB
https://packages.microsoft.com/debian/10/prod/pool/main/a/aziot-edge/aziot-edge_1.2.9-1_armhf.deb = 425,742 bytes (415KB !!)

**Comment by damonbarry** [comment]
@daveinci I'm on the IoT Edge team. Since Debian 10 is a [Tier 2 platform for IoT Edge](https://learn.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-1.4#tier-2), the place to get binaries is our [GitHub Releases](https://github.com/Azure/azure-iotedge/releases?q=1.4&expanded=true) page. 1.4 LTS is the currently supported version. The most recent release of the host binaries is 1.4.16.

I believe uploading a Debian 10 armhf binary to packages.microsoft.com was an oversight, and you're not the first to have problems with it. I'll look into getting it removed.
