### ISSUE TITLE
Add Debian and RPM packages of Microsoft's AZNFS-mount to listed packages

### ISSUE THREAD

**Issue by palashvij-msft** [microsoft/linux-package-repositories#81]
Hey, AZNFS-Mount is Utility for correctly handling endpoint IP address changes for Azure Blob NFS mounts. We wanted to publish the debian and rpm packages of our tool to repository. 

Here's the repo and latest version packages: https://github.com/Azure/AZNFS-mount/tree/0.1.109

Can you share the further steps?

Thanks
Palash

**Comment by daviddavis** [comment]
I synced up with @palashvij-msft internally to get the AZNFS-mount team started on onboarding to packages.microsoft.com.
