### ISSUE TITLE
edge yumrepos config.repo file content conflicting protocol with port

### ISSUE THREAD

**Issue by bcunninghaminfor** [microsoft/linux-package-repositories#82]
**Describe the issue**
Since yesterday around 1730 hours UTC, we have had failures installing edge via yum.  It appears the config.repo file (https://packages.microsoft.com/yumrepos/edge/config.repo) has conflicting protocol and port.  Possibly should be https

**When did the issue occur?**
September 12 around 1730 hours UTC

**If applicable, what package did you attempt to install, and from which repo?**
yum microsoft-edge-stable

**Steps to Reproduce**
rpm --import https://packages.microsoft.com/keys/microsoft.asc     && curl https://packages.microsoft.com/yumrepos/edge/config.repo > /etc/yum.repos.d/microsoft-edge-dev.repo     && yum --nogpgcheck install -y microsoft-edge-stable

**Actual Result**
 http://packages.microsoft.com:443/yumrepos/edge/repodata/repomd.xml: [Errno 14] HTTP Error 400 - Bad Request
Trying other mirror.

**Expected Result**
Successful package install

**Screenshots**
![image](https://github.com/microsoft/linux-package-repositories/assets/143212270/dca6a559-5fe1-438c-b301-226de2fc0b79)

**Additional context**
Our script has not changed and we noticed microsoft-edge-stable-116.0.1938.81-1.x86_64.rpm was uploaded at September 12 1722 hours UTC but the repodata directory was updated at 1858 hours UTC.  We had a successful install in between these times.

**Comment by daviddavis** [comment]
https://packages.microsoft.com/yumrepos/edge/config.repo should be fixed now. We're clearing other config.repo files from our cache as well.

**Comment by sdherr** [comment]
All affected config.repo files / regions have been purged, this issue should be completely resolved.
