### ISSUE TITLE
Issue with Debian 9 Distro name

### ISSUE THREAD

**Issue by kd-issa** [microsoft/linux-package-repositories#83]
**Describe the issue**

Upon provisioning of an azure arc edge server on Debian 9. The install_linux_azcmagent.sh script fails to download the proper package.
The issue is on line #504  :  curl https://packages.microsoft.com/config/${deb_distro}/packages-microsoft-prod.deb -o ${tempdir}/packages-microsoft-prod.deb

on line#353:  deb_distro=debian/9

however the url substituted would not be valid and the actual url  should add /multiarch which becomes  https://packages.microsoft.com/config/debian/9/multiarch/packages-microsoft-prod.deb

**Comment by mbearup** [comment]
@kd-issa thanks for reporting this.
Note that this github instance is focused on the distribution of repos/packages. We do not maintain the shell script in question. But we've tracked down the appropriate team and relayed your feedback to them.
