### ISSUE TITLE
Debian 11 unixodbc 2.3.11-2 AMD64 binaries have mismatched checksums 

### ISSUE THREAD

**Issue by erickpeirson** [microsoft/linux-package-repositories#88]
**Describe the issue**

In the Debian 11 unixodbc 2.3.11-2 AMD64 build at https://packages.microsoft.com/debian/11/prod/pool/main/u/unixodbc/, the checksums associated with the package do not match binaries included therein.

```
# cat /var/lib/dpkg/info/unixodbc.md5sums
852b1dddca9b1715e413e204d264ef1d  /usr/share/man/man7/unixODBC.7
2eb92461e82f714a967ea411cd83733f  /usr/share/man/man1/isql.1
6d4417413511f394ea82dc90df0ee769  /usr/share/man/man1/iusql.1
d62e3517b4bd1e3602ff015bf3b27897  /usr/bin/iusql
8959d90e615b19d1e5881dbd138e6fe3  /usr/bin/isql

# md5sum /usr/bin/iusql
f79389502c1d33ac844bb90d95d5399e  /usr/bin/iusql
# md5sum /usr/bin/isql
7a38d98564587fead939c17f8caca00f  /usr/bin/isql
```

This is flagged as a critical security issue in some systems. Build 2.3.11-1 is not affected.

**When did the issue occur?**

This appears to have been introduced when build `2.3.11-2` was published on 10 October, 2023.

**If applicable, what package did you attempt to install, and from which repo?**

**Steps to Reproduce**

- Install unixodbc 2.3.11-2 AMD64 from https://packages.microsoft.com/debian/11/prod/pool/main/u/unixodbc/
- Compare the checksums in `/var/lib/dpkg/info/unixodbc.md5sums` to the checksums of the binaries actually installed

**Actual Result**

Checksums for `/usr/bin/iusql` and `/usr/bin/isql` do NOT match the values in `unixodbc.md5sums`

**Expected Result**

Checksums for `/usr/bin/iusql` and `/usr/bin/isql` DO match the values in `unixodbc.md5sums`

**Comment by mbearup** [comment]
@erickpeirson thanks for reporting this discrepancy. We've relayed your findings to the SQL maintainers, who will follow up with a mitigation plan/ETA.
FWIW, one of our ongoing investments is to verify/enforce package quality, to prevent discrepancies like  this from occurring in the future.

**Comment by v-chojas** [comment]
As you have seen, this issue does not prevent the installation nor affect the usability of the package itself, hence why our testing didn't discover it. According to https://manpages.debian.org/bookworm/dpkg-dev/deb-md5sums.5.en.html the hashes are "not for any kind of security purpose."

We should have a fix for this published in around a week. Apologies for the inconvenience.

**Comment by v-chojas** [comment]
@erickpeirson 2.3.11-3 has been released with the fix.

**Comment by erickpeirson** [comment]
@v-chojas Fantastic! Thanks for the quick fix
