### ISSUE TITLE
No ipv6 on packages.microsoft.com

### ISSUE THREAD

**Issue by leecow** [microsoft/linux-package-repositories#89]
[ Transferring issue from https://github.com/dotnet/core/issues/7435 ]

In reference to the closed issue: https://github.com/dotnet/core/issues/3016

It's been more than 6 months and packages.microsoft.com still hasn't got an AAAA record.
It doesn't seem like a herculean task to get this done?

The reason for supporting this is: Mitigate IPv4 scarcity.
Most infrastructure environments (which need these packages) have no need for IPv4. The lack of an AAAA record on packages.microsoft.com is stalling this transition.

Could someone please arrange this?

Thank you in advance!

**Comment by JSXRED** [comment]
It's really a big pain point. Our server purely communicate ipv6 internal. Over 20 server have an ipv4 apt proxy configured just to be able to load .NET. We have been waiting for over a year to get rid of that. The first Ticket was open 2019 about this topic. It's unbelievable that it's cost more than 4 years now. Especially because most Azure services can already do ipv6 now.

**Comment by mbearup** [comment]
@JSXRED thanks for bringing this to our attention. We're in the process of revamping our content delivery strategy, and will include IPv6 in our plan going forward.

**Comment by mbearup** [comment]
As mentioned in #50, we're transitioning to Azure Front Door (AFD) for packages.microsoft.com content delivery. An added benefit is ipv6 support.
As of today, AFD is serving all of our traffic in APAC. Assuming no obstacles, it will be rolled out to the rest of the world by end of next week.
```
$ nslookup packages.microsoft.com
...
packages.microsoft.com  canonical name = apt-geofence-parent.trafficmanager.net.
apt-geofence-parent.trafficmanager.net  canonical name = pmc-prod-afd-endpoint-evdhh8f8byhsezfp.b01.azurefd.net.
pmc-prod-afd-endpoint-evdhh8f8byhsezfp.b01.azurefd.net  canonical name = shed.dual-low.part-0045.t-0009.t-msedge.net.
shed.dual-low.part-0045.t-0009.t-msedge.net     canonical name = part-0045.t-0009.t-msedge.net.
Name:   part-0045.t-0009.t-msedge.net
Address: 13.107.246.73
Name:   part-0045.t-0009.t-msedge.net
Address: 13.107.213.73
Name:   part-0045.t-0009.t-msedge.net
Address: 2620:1ec:46::73
Name:   part-0045.t-0009.t-msedge.net
Address: 2620:1ec:bdf::73
```
