### ISSUE TITLE
azcmagent not found

### ISSUE THREAD

**Issue by aangelisc** [microsoft/linux-package-repositories#90]
**Describe the issue**

Cannot install the `azcmagent` package from any repository.

**When did the issue occur?**

Today

**If applicable, what package did you attempt to install, and from which repo?**
`azcmagent` from Ubuntu and Fedora repositories

**Steps to Reproduce**

Run `wget https://aka.ms/azcmagent -O ~/install_linux_azcmagent.sh 2>&1` and then `bash ~/install_linux_azcmagent.sh`
**Actual Result**
```
Reading state information... Done
E: Unable to locate package azcmagent
/root/install_linux_azcmagent.sh: error installing azcmagent (exit code: 100). See 'apt' command logs for more information.
```
**Expected Result**
`azcmagent` package is installed

**Screenshots**

**Additional context**

Running in docker containers

**Comment by daviddavis** [comment]
It looks like the azcmagent is available for Ubuntu e.g.:
https://packages.microsoft.com/repos/microsoft-ubuntu-jammy-prod/pool/main/a/azcmagent/

While I see the package in the CentOS and RHEL repos, I don't see it in the Fedora repos. But when I look at the install script, it doesn't look it supports Fedora.

**Comment by aangelisc** [comment]
That works! @daviddavis my bad I was running the wrong platform (`arm64`). Thank you 😊

**Comment by edyoung** [comment]
You can see the supported linux distributions for this package here: https://learn.microsoft.com/en-us/azure/azure-arc/servers/prerequisites#supported-operating-systems
