### ISSUE TITLE
Ubuntu 23.10 support

### ISSUE THREAD

**Issue by tflori** [microsoft/linux-package-repositories#92]
**Describe the issue**
Ubuntu 23.10 is missing in https://packages.microsoft.com as well as in https://packages.microsoft.com/config . I'm unable to install intune

**When did the issue occur?**
after upgrading to ubuntu 23.10

**Comment by jasonzio** [comment]
This has been resolved with respect to the repos themselves. However, it doesn't appear that the intune folks have published a package for 23.10 so far. I will pass them a message asking them to look into this, but you may get faster action contacting Microsoft support for the intune product itself.

**Comment by benferse** [comment]
Thanks for reaching out @tflori. The Intune client has official support only for Ubuntu LTS releases. Early next year you can expect to see packages for 24.04 starting to roll out.
