### ISSUE TITLE
Ubuntu 22.04 mirror corrupted?

### ISSUE THREAD

**Issue by hartwork** [microsoft/linux-package-repositories#97]
**Describe the issue**

Hi! :wave: 

(I was sent to report here from here original https://github.com/actions/runner-images/issues/8846 .)

The symptom is this:

```console
# sudo apt-get update
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Get:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [3531 B]
Hit:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:5 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease
Hit:7 https://apt.llvm.org/jammy llvm-toolchain-jammy-17 InRelease
Hit:8 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease
Reading package lists...
E: Repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease'
   changed its 'Origin' value from 'microsoft-ubuntu-jammy-prod jammy' to 'Pulp 3'  <-- !!!
E: Repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease'
   changed its 'Label' value from 'microsoft-ubuntu-jammy-prod jammy' to ''
W: http://apt.llvm.org/jammy/dists/llvm-toolchain-jammy-17/InRelease: Key is stored
   in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section
   in apt-key(8) for details.
Error: Process completed with exit code 100.
```
(from https://github.com/hartwork/ttyplot/actions/runs/6931337323/job/18852856440)

It happens sometimes, but not every time.

I had not heard about [Pulp](https://pulpproject.org/) or [Pulp 3](https://pulpproject.org/about-pulp-3/) until today, but I am surprised to hear about it from that file :smile:

Is Azure transitioning to Pulp under the hood or is this content corruption on a deeper level like a damaged hard disk or something? Any ideas?

Thanks and best, Sebastian

**When did the issue occur?**
I first saw it today, at the very CI run linked above, I think.

**If applicable, what package did you attempt to install, and from which repo?**
n/a

**Steps to Reproduce**

Run `sudo apt-get update` in a GitHub Actions CI based on image `ubuntu-22.04` a few times, and be "lucky" to see the issue, does not happen every time, probably there is load balancing in front of multiple mirrors and not all mirrors are affected.

**Actual Result**
The error above.

**Expected Result**
No error.

**Screenshots**

n/a

**Additional context**

GitHub Actions

**Comment by gaelworkstaff** [comment]
Had the same issue on a couple of GitHub Actions this morning.

**Comment by mbearup** [comment]
@hartwork we're tracking this via #96.
We've implemented a central fix and re-published all repos, so this should be resolved. Some customers have reported a delay in resolution due to cache latency, but the issues have generally been resolving over time.
If you're still experiencing this issue, let us know which IP you're hitting so we can investigate further.
