### ISSUE TITLE
E: Repository 'https://packages.microsoft.com/repos/azurecore bionic InRelease' changed its 'Origin' value from 'azurecore bionic' to 'Pulp 3'

### ISSUE THREAD

**Issue by PHPirates** [microsoft/linux-package-repositories#98]
**Describe the issue**

When I execute the following commands on my Ubuntu 18.04:

```
wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O /tmp/packages-microsoft-prod.deb
sudo dpkg --force-confold -i /tmp/packages-microsoft-prod.deb
sudo apt-get update
```

then sometimes this is the result:

```
(...)
Reading package lists... Done 

E: Repository 'https://packages.microsoft.com/repos/azurecore bionic InRelease' changed its 'Origin' value from 'azurecore bionic' to 'Pulp 3'
E: Repository 'https://packages.microsoft.com/repos/azurecore bionic InRelease' changed its 'Label' value from 'azurecore bionic' to ''
```

On a different machine, a similar error occurs:

```
Reading package lists... Done
E: Repository 'https://packages.microsoft.com/debian/10/prod buster InRelease' changed its 'Origin' value from 'microsoft-debian-buster-prod buster' to 'Pulp 3'
E: Repository 'https://packages.microsoft.com/debian/10/prod buster InRelease' changed its 'Label' value from 'microsoft-debian-buster-prod buster' to ''
```

**When did the issue occur?**

This afternoon, yesterday it still worked.

**If applicable, what package did you attempt to install, and from which repo?**
Not yet, apt update already fails on azurecore

**Steps to Reproduce**

Just the three commands above

**Actual Result**
`apt-get update` exits with exit code 100 and the error above, about half of the times I tried

**Expected Result**
No error

**Screenshots**

**Additional context**

I reproduced the problem on a new machine

**Comment by jasonzio** [comment]
This should be fully resolved now. You may need to fully clear apt caches for the packages.microsoft.com repo(s) you care about.
